cache map ready for PR
treeverse/lakeFS pull request #1010
Opened 2020-12-07 14:41 UTC by tzahij

2020-12-08 08:07 UTC, arielshaqed requested changes
1. Why do we need our own cache?  (_This is the single most important comment; let's answer it *before* we do anything else!_)
2. This implementation is not thread-safe.
3. AFAICT this is a decaying LFU, maybe write that down somewhere so the next person to try to figure it out has an easier time reading about it?
4. This implementation has poor performance.  In particular it has an O(n) code path (which is even O(n) amortized) during get.  I don't understand why that code path is required, see comment there for an alternative.  It also has an O(n) code path during set, which once for every cache miss.
5. There is no facility for monitoring this cache.  It will be impossible to know how well a cache is doing when it is inobservable.

2020-12-08 08:07 UTC, arielshaqed commented on forest/cache_map/cache_map_manger.go
> +	*h = old[0 : n-1]
I don't understand why we need `old`, if we never modify `*h` until the last line.
```suggestion
	n := len(*h)
	x := (*h)[n-1]
	*h = *h[0 : n-1]
```

2020-12-08 08:07 UTC, arielshaqed commented on forest/cache_map/cache_map_manger.go
> +package cachemap
I think the filename is misspelled.  I am also confused what "man[a]ger" here means, it looks like a cache.

2020-12-08 08:09 UTC, arielshaqed commented
Also please rename the PR to state what it does.  I don't think we need to go full [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), but e.g. https://chris.beams.io/posts/git-commit/ is a good simple guide.

2020-12-08 09:35 UTC, ozkatz commented
Iterating on what @arielshaqed asked - why do we need another cache implementation in lakeFS?
Ideally we should standardize on *one* unless we have a concrete reason to do so.

2020-12-12 08:11 UTC, nopcoder commented on forest/cache_map/cache_map_manger.go
> +func (h *heapItemsType) Pop() interface{} {
missed this one... which check? nil?

2020-12-18 00:04 UTC, tzahij commented
> 1. Why do we need our own cache?  (_This is the single most important comment; let's answer it _before_ we do anything else!_)
I am sorry to say you are totally right
> 2. This implementation is not thread-safe.
right. It is easy to make it thread safe, but as you said before, that would be an exercise in futility
> 3. AFAICT this is a decaying LFU, maybe write that down somewhere so the next person to try to figure it out has an easier time reading about it?
right
> 4. This implementation has poor performance.  In particular it has an O(n) code path (which is even O(n) amortized) during get.  I don't understand why that code path is required, see comment there for an alternative.  It also has an O(n) code path during set, which once for every cache miss.
I beg to differ. it is O(1) for get and set. the decay process is called only once in NumberOfCaheEntries calls and may be tuned.  Eviction is rarely called, and in is O(n) + O(h*log h) where h is the number of entries to be evicted,
> 5. There is no facility for monitoring this cache.  It will be impossible to know how well a cache is doing when it is inobservable.
right

2020-12-20 09:53 UTC, ozkatz commented
Since there doesn't seem to be a concensus on the necesaity of this, I'm closing it for now. If anyone has good reasoning to do so, please reopen :)

2020-12-20 09:53 UTC, closed without merging

2020-12-20 11:52 UTC, tzahij commented
agreed

________________________________
From: Oz Katz <notifications@github.com>
Sent: Sunday, December 20, 2020 9:53 AM
To: treeverse/lakeFS <lakeFS@noreply.github.com>
Cc: tzahij <tzahij@hotmail.com>; Author <author@noreply.github.com>
Subject: Re: [treeverse/lakeFS] cache map ready for PR (#1010)


Since there doesn't seem to be a concensus on the necesaity of this, I'm closing it for now. If anyone has good reasoning to do so, please reopen :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/treeverse/lakeFS/pull/1010#issuecomment-748586126>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJT2CKCYSQSX35PK2WFF6TSVXCRNANCNFSM4UQRT5ZQ>.