Feature/tree basic
treeverse/lakeFS pull request #1013
Opened 2020-12-08 08:54 UTC by tzahij

Very raw

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_reader.go
> +		return nil, ErrPathBiggerThanMaxPath
Not sure this is a special case: the next can just return false

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_reader.go
> +	t, exists := trees.TreesMap.Get(string(treeID))
this function should use TierFS in the future, right?

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_reader.go
> +	if t.currentIter == nil {
I think we're keeping the error on t.err

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_reader.go
> +	partNum := findPartNumForPath(t.TreeParts, start)
need to unset t.closed here

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_reader.go
> +		t.currentPart = partNum
If we arrive here after an error, currentIter can be closed

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_writer.go
> +	return !(tw.activeWriter == nil)
```suggestion
	return tw.activeWriter != nil
```

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_writer.go
> +	fnvHash.Write(key)
what is this hash for? is it intended to create parts in different sizes?

2020-12-08 14:55 UTC, johnnyaug commented on forest/tree/tree_writer.go
> +	closeResults, err := tw.closeAsync.Wait()
at this point, the activeWriter was already closed?

2020-12-09 13:16 UTC, itaiad200 requested changes

2020-12-09 13:16 UTC, itaiad200 commented on forest/tree/tree_writer.go
> +	err = ioutil.WriteFile("tree_"+string(treeID)+".json", treeBytes, 0666)
Pyramid ;) ?

2020-12-09 13:16 UTC, itaiad200 commented on forest/tree/tree_writer.go
> +type TreeWriter struct {
I think the TreeWriter is coupled to `Apply` more than we want it to be.
Some of the inner logic (like flushIterToNewTree) is fine for `Apply`, but might differ for `Merge` for example.

2020-12-09 14:33 UTC, johnnyaug commented on forest/tree/tree_reader.go
> +func (trees *TreesRepoType) NewScannerFromID(treeID gr.TreeID, start gr.Key) (*treeIterator, error) {
Change "Scanner" to "Iterator"

2020-12-28 10:10 UTC, ozkatz commented
Work from this PR was adapted and merged in a different set of PRs. Closing for now.

2020-12-28 10:10 UTC, closed without merging