entry catalog that uses graveler
treeverse/lakeFS pull request #1058
Opened 2020-12-14 12:30 UTC by nopcoder

2020-12-14 13:31 UTC, guy-har approved these changes
Looks great.

One thing, rocks should not be aware of tombstones

2020-12-14 13:31 UTC, guy-har commented on catalog/rocks/entry.go
> +}
rocks should consider about tombstones, It could use graveler.delete directly.
graveler.delete will create a tombstone in case it is needed

2020-12-14 13:32 UTC, guy-har requested changes
Looks great.

One thing, rocks should not be aware of tombstones

2020-12-14 13:48 UTC, johnnyaug approved these changes

2020-12-14 13:48 UTC, johnnyaug commented on catalog/rocks/entry_catalog.go
> +	db graveler.Graveler
I wouldn't call it db. If not `graveler`, then maybe `store`?

2020-12-14 13:48 UTC, johnnyaug commented on catalog/rocks/entry_catalog_test.go
> +			if (err != nil) != tt.wantErr {
aren't we supposed to use errors.Is?
not sure anymore

2020-12-14 13:48 UTC, johnnyaug commented on catalog/rocks/entry_catalog.go
> +	ent, err := ValueToEntry(val)
don't want to just return `ValueToEntry`?

2020-12-16 09:32 UTC, guy-har approved these changes

2020-12-16 09:32 UTC, guy-har commented on catalog/rocks/entry_test.go
> +		Metadata:     nil,
add metadata to test

2020-12-16 12:11 UTC, merged