Add graveler commit and branch lock
treeverse/lakeFS pull request #1077
Opened 2020-12-17 07:03 UTC by guy-har

2020-12-17 07:06 UTC, guy-har commented
I accidentally pushed an irrelevant commit (the first one) so I fixed it in the last commit

2020-12-17 13:07 UTC, nopcoder requested changes

2020-12-17 13:07 UTC, nopcoder commented on graveler/graveler_test.go
> +	_, err = bl.RequestWrite("a", defaultBranchID)
you can't assume that you got the goroutine into the point passed metadata update

2020-12-20 14:29 UTC, nopcoder approved these changes

2020-12-20 14:49 UTC, guy-har commented
closes #1054

2020-12-20 14:50 UTC, merged