Read ristretto cleanup during test that fails it
treeverse/lakeFS pull request #1101
Opened 2020-12-24 15:23 UTC by itaiad200

2020-12-24 20:43 UTC, nopcoder commented
Suggestion - the default FS uses the ristreto cache which as I understand you want to abstract for testing.
You already have an evict interface which we already implemented by ristreto cache.
Instead of creating a function callback for factory of this type, make the interface public and accept it as part of the config.
Do not require it.
In case it is nil - create new restreto cache.
This way we have fewer callbacks, less code and the user of the FS doesn't need to care about it unless it is part of his/her agenda to override the default evict implementation.

2020-12-24 20:45 UTC, nopcoder requested changes
let me know what you think about my suggestion to simplify the use of FS

2020-12-25 16:31 UTC, itaiad200 commented
@nopcoder Agreed, changed the FS.

2020-12-25 22:02 UTC, nopcoder approved these changes

2020-12-26 13:41 UTC, merged