Tags create list show delete through open API and CLI
treeverse/lakeFS pull request #1323
Opened 2021-01-25 22:05 UTC by nopcoder

API and CLI for tag list/create/delete/show

 - TODO: test code

2021-01-27 10:00 UTC, johnnyaug requested changes

2021-01-27 10:19 UTC, nopcoder commented on catalog/rocks/cataloger.go
> +	if len(tags) >= limit {
1. collecting limit+1 in the loop above
2. fixing this one - need to check > limit

2021-01-27 11:00 UTC, nopcoder commented on cmd/lakectl/cmd/tag.go
> +			CommitID: swag.String(tag),
1. The name `tag` is not good - will rename to commitRef. 
2. Let me know if you think we should change the API as the type 'ref' is used for input and output. while in the input we can accept short commit which we will resolve and in response, we will send the full commit.
3. The CLI takes the tag name from the uri parse, ex: lakefs://repo@v1.0 (tag v1.0)

2021-01-27 11:09 UTC, johnnyaug commented on cmd/lakectl/cmd/tag.go
> +			CommitID: swag.String(tag),
I understand. So maybe change `u` to tagUri

2021-01-27 11:10 UTC, johnnyaug commented on cmd/lakectl/cmd/tag.go
> +			CommitID: swag.String(tag),
I'm currently going over all lakectl API, for now just renaming is enough

2021-01-27 11:43 UTC, nopcoder commented on cmd/lakectl/cmd/tag.go
> +		Fmt("created tag '%s'\n", u.Ref)
1. Fixed
2. Updated the api spec to support this one

2021-01-28 08:36 UTC, johnnyaug requested changes

2021-01-28 08:36 UTC, johnnyaug commented on catalog/rocks/fake_graveler_test.go
> +/// BARAK
nice touch

2021-01-28 08:36 UTC, johnnyaug commented on cmd/lakectl/cmd/tag.go
> +	Use:   "create <ref uri> <commit ref>",
the first one should be `<tag uri>`

2021-01-28 08:36 UTC, nopcoder commented on catalog/rocks/fake_graveler_test.go
> +/// BARAK
ha ha - forgot my text marker :)

2021-01-28 08:40 UTC, johnnyaug approved these changes

2021-01-28 09:40 UTC, merged