Fix/commit compare error #1286
treeverse/lakeFS pull request #1330
Opened 2021-01-26 10:22 UTC by shamikakumar

Fixes #1286. Changed the api call to refs which handles both branches&commits. Also removed the if-else statement because the api handles the condition for comparing a branch/commit to itself.

2021-01-27 08:55 UTC, johnnyaug requested changes
Hey @shamikakumar, thank you for your effort!

The `branches/diff` and `refs/diff` APIs are entirely different things: the first is used to show all _uncommitted_ changes (mainly for the Changes tab), and the second one compares two _commits_.
Your change removes the functionality of viewing uncommitted changes. You will need to make a less intrusive change.

Thanks again, and feel free to consult with me on Slack

2021-01-27 11:41 UTC, shamikakumar commented
Hi @johnnyaug thanks for clarifying! I misunderstood what the APIs were doing. I see now what consequences that had. I've modified my PR so as to not call the diff api when the sources are the same. Do review and let me know.

2021-01-28 08:58 UTC, johnnyaug approved these changes

2021-01-28 09:02 UTC, merged

2021-01-28 09:02 UTC, johnnyaug commented
Thanks @shamikakumar for your contribution!