fix arg order in merge cmd
treeverse/lakeFS pull request #1341
Opened 2021-01-27 11:00 UTC by johnnyaug

2021-01-27 11:15 UTC, ozkatz commented
There are a few more breaking changes that I'd like to make to the cli. We should probably batch them together.

2021-02-01 05:52 UTC, itaiad200 approved these changes
Approved, but sync with @ozkatz before you pull for other breaking changes to the CLI.

2021-02-01 11:24 UTC, itaiad200 requested changes
That is one confusing referencing shenanigans! 
I think you got some ours/theirs references mixed-up.

2021-02-01 11:24 UTC, itaiad200 commented on catalog/rocks/cataloger.go
> +func (c *cataloger) Merge(ctx context.Context, repository string, theirs string, ours string, committer string, message string, metadata catalog.Metadata) (*catalog.MergeResult, error) {
use branch in var name.

2021-02-01 11:24 UTC, itaiad200 commented on catalog/rocks/entry_catalog.go
> +		commitParams.Message = fmt.Sprintf("Merge '%s' into '%s'", ours, theirs)
Isn't this the other way around?

2021-02-01 11:24 UTC, itaiad200 commented on catalog/rocks/entry_catalog.go
> +func (e *EntryCatalog) Merge(ctx context.Context, repositoryID graveler.RepositoryID, theirs graveler.BranchID, ours graveler.Ref, commitParams graveler.CommitParams) (graveler.CommitID, graveler.Dif
How did the types change?

2021-02-01 11:24 UTC, itaiad200 commented on cmd/lakectl/cmd/merge.go
> +		sourceRef := uri.Must(uri.Parse(args[0]))
Why another terminology? Let's stick with either source/destination or theirs/ours (I like the first one better but that's just me)

2021-02-01 11:24 UTC, itaiad200 commented on graveler/graveler.go
> +	res, err := g.branchLocker.MetadataUpdater(ctx, repositoryID, theirs, func() (interface{}, error) {
Did you switch the lock on purpose?

2021-02-01 11:58 UTC, itaiad200 approved these changes
LGTM!

2021-02-01 11:58 UTC, itaiad200 commented on catalog/rocks/fake_graveler_test.go
> +func (g *FakeGraveler) Merge(ctx context.Context, repositoryID graveler.RepositoryID, theirs graveler.BranchID, ours graveler.Ref, _ graveler.CommitParams) (graveler.CommitID, graveler.DiffSummary, e
Forgot one.

2021-02-01 11:58 UTC, itaiad200 commented on graveler/graveler.go
> +	// Compare returns the difference between 'source' and 'destinationn', relative to a merge base 'base'.
```suggestion
	// Compare returns the difference between 'source' and 'destination', relative to a merge base 'base'.
```

2021-02-01 13:18 UTC, merged