Add Azure adapter
treeverse/lakeFS pull request #1444
Opened 2021-02-10 12:15 UTC by guy-har

2021-02-10 14:51 UTC, johnnyaug commented on block/azure/chunkwriting.go
> +	sd := strconv.Itoa(int(cp.reader.CopiedSize)) + "\n"
IIUC, the size file contains only a single line, that has the total size of the part.
If so, I would use the same files for IDs and size - e.g. with the first line representing the size.

2021-02-10 14:51 UTC, johnnyaug commented on block/azure/chunkwriting.go
> +	_, err = cp.toSizes.StageBlock(cp.ctx, base64Etag, strings.NewReader(sd), cp.o.AccessConditions.LeaseAccessConditions, nil, cp.o.ClientProvidedKeyOptions)
Suggestion:
Use a struct:
```go
type PartInfo struct {
  blockIDs []string `json:"block_ids"`
  size int `json:"size"`
}
```

Then, have just one file for all the blockInfos, and read it with one method and not two.

2021-02-15 07:21 UTC, nopcoder requested changes
A partial review looking into the adapter.go now

2021-02-15 10:59 UTC, nopcoder requested changes

2021-02-15 10:59 UTC, nopcoder commented on block/azure/adapter.go
> +}
Think we just need one function that builds the container URL object and not a lot of helpers that will continue to call the base function that will parse the URL again and again

2021-02-15 10:59 UTC, nopcoder commented on block/azure/adapter.go
> +	bodyStream := downloadResponse.Body(a.configurations.retryReaderOptions)
Close

2021-02-15 11:12 UTC, nopcoder commented on block/azure/adapter.go
> +	}
This one should probably do the same using Go's error package
```suggestion
	var storageErr azblob.StorageError
	if errors.As(err, &storageErr)  && storageErr.ServiceCode() == azblob.ServiceCodeBlobNotFound {
		return false, nil
	} else if err != nil {
		return false, err
	}
```

2021-02-15 12:57 UTC, nopcoder commented on block/azure/adapter.go
> +	_ = a.log().WithFields(logging.Fields{
need to store or print something

2021-02-15 12:59 UTC, guy-har commented on block/azure/adapter.go
> +	BlockstoreType          = "wasb"
Windows Azure Storage Blob

2021-02-15 13:12 UTC, guy-har commented on block/factory/build.go
> +	return azure.NewAdapter(p, accountName), nil
pipeline is the azure client

credentials are used to initiate the pipeline, The adapter does need to hold the credentials, but does need the account name

2021-02-15 13:19 UTC, nopcoder requested changes

2021-02-15 13:19 UTC, nopcoder commented on block/azure/adapter.go
> +	metaBlockIDs := make([]string, 0)
```suggestion
	metaBlockIDs := make([]string, 0, len(parts))
```

2021-02-15 13:19 UTC, nopcoder commented on block/azure/adapter.go
> +	stageBlockIDs, err := a.getMultipartIDs(containerName, fileName, metaBlockIDs)
check err or ignore

2021-02-15 13:19 UTC, nopcoder commented on block/azure/adapter.go
> +	etag = etag[1 : len(etag)-2]
```suggestion
	etag = strings.Trim(etag, "\"")
```

2021-02-15 13:19 UTC, nopcoder commented on block/azure/adapter.go
> +	metaBlockIDs := make([]string, 0)
```suggestion
	metaBlockIDs := make([]string, 0, len(parts))
```

2021-02-15 13:19 UTC, nopcoder commented on block/azure/adapter.go
> +		a.log().WithError(err).Warn("Failed to delete multipart ids data file")
without containerName, fileName we have no idea which one failed

2021-02-15 13:19 UTC, nopcoder commented on block/azure/adapter.go
> +	bodyStream := downloadResponse.Body(a.configurations.retryReaderOptions)
Close

2021-02-15 13:19 UTC, nopcoder commented on block/azure/adapter.go
> +		a.log().WithError(err).Warn("Failed to delete multipart size data file")
adding containerName and fileName will help identify the call

2021-02-15 13:19 UTC, nopcoder commented on block/azure/chunkwriting.go
> +func defaults(u *azblob.UploadStreamToBlockBlobOptions) error {
think we can remove this part and just initialize NewStaticBuffer

2021-02-15 13:19 UTC, nopcoder commented on block/azure/chunkwriting.go
> +// TODO(someone): The existing model provides a buffer size and buffer limit as limiting factors.  The buffer size is probably
consider removing their TODOs

2021-02-16 08:26 UTC, nopcoder approved these changes

2021-02-16 17:06 UTC, merged