Enrich webhook output file
treeverse/lakeFS pull request #1519
Opened 2021-02-24 16:37 UTC by itaiad200

closes #1517

2021-02-24 16:48 UTC, nopcoder commented on actions/webhook.go
> +func writeOutput(ctx context.Context, writer *HookOutputWriter, req *http.Request, resp *http.Response, reqBody []byte) error {
https://golang.org/pkg/net/http/httputil
I was thinking we should use dump request and response

2021-02-24 16:49 UTC, nopcoder requested changes

2021-02-24 16:49 UTC, nopcoder commented on actions/service_test.go
> +	"github.com/stretchr/testify/require"
remove empty line

2021-02-25 08:51 UTC, nopcoder requested changes

2021-02-25 08:51 UTC, nopcoder commented on actions/service_test.go
> +	bytes, err := ioutil.ReadAll(outputReader)
need to capture this one in the DoAndReturn - can't assume the reader will be valid at this point

2021-02-25 08:51 UTC, nopcoder commented on actions/service_test.go
> +	require.Greater(t, len(rows), 10)
You can use bytes.Split if you just want to count rows, and prevent the string()

2021-02-25 08:51 UTC, nopcoder commented on actions/webhook.go
> +	return writer.OutputWrite(ctx, buf, int64(buf.Len()))
```suggestion
	var buf bytes.Buffer
	dumpReq, err := httputil.DumpRequestOut(req, true)
	if err != nil {
		buf.WriteString("Error during request dump: " + err.Error() + "\n")
		return err
	}
	_, err = buf.WriteString("Request:\n")
	if err != nil {
		return err
	}
	_, err = buf.Write(dumpReq)
	if err != nil {
		return err
	}

	dumpResp, err := httputil.DumpResponse(resp, true)
	if err != nil {
		return err
	}
	_, err = buf.WriteString("\n\nResponse:\n")
	if err != nil {
		buf.WriteString("Error during response dump: " + err.Error() + "\n")
		return err
	}
	_, err = buf.Write(dumpResp)
	if err != nil {
		return err
	}

	_, err = buf.WriteString("\nRequest duration: " + elapsed.String() + "\n")
	if err != nil {
		return err
	}
	return writer.OutputWrite(ctx, &buf, int64(buf.Len()))
```

2021-02-25 08:51 UTC, nopcoder commented on actions/webhook.go
> +	if _, err := reqReader.Seek(0, 0); err != nil {
why?

2021-02-25 10:55 UTC, itaiad200 commented on actions/webhook.go
> +	return writer.OutputWrite(ctx, buf, int64(buf.Len()))
Did something similar, have a look.

2021-02-25 10:57 UTC, itaiad200 commented on actions/webhook.go
> +	if _, err := reqReader.Seek(0, 0); err != nil {
Otherwise `httputil.DumpRequestOut` returns an error.

2021-02-25 14:45 UTC, nopcoder approved these changes

2021-02-25 15:02 UTC, merged