WIP: remove entry catalog
treeverse/lakeFS pull request #1576
Opened 2021-03-06 12:05 UTC by ozkatz

This seems to work OK but tests aren't passing: seems that I've been able to reincarnate #1349 as I'm seeing the exact same errors happening in all the same places.

For reference: the only change I made that I can think about having anything to do with Pebble's cache, was moving its initialization from the now non-existent EntryCatalog to RocksCatalog, both doing the exact same thing and both `defer`ing an `Unref()` for it.

2021-03-07 18:30 UTC, nopcoder requested changes

2021-03-07 18:30 UTC, nopcoder commented on catalog/catalog.go
> +	tierFSParams, err := cfg.Config.GetCommittedTierFSParams(ctx)
not related to this pr - think we need to extract this one out.  The Config should hold everything needed in order to instantiate a new catalog.

2021-03-07 18:30 UTC, nopcoder commented on catalog/catalog.go
> +	return nil
go-multierror - we like to close them all

2021-03-07 18:30 UTC, nopcoder commented on graveler/sstable/range_manager.go
> +// If key is not found, (nil, ErrKeyNotFound) is returned.
nice

2021-03-08 11:09 UTC, ozkatz commented
@nopcoder fixed all comments, PTAL

2021-03-08 11:11 UTC, nopcoder approved these changes

2021-03-08 12:07 UTC, merged