added random write abuse command and created an initial sizing guide
treeverse/lakeFS pull request #1602
Opened 2021-03-10 09:49 UTC by ozkatz

closes #1523

2021-03-10 12:57 UTC, itaiad200 requested changes
Really detailed guide, adds a lot of value to the users.

Requesting changes mostly due to few nits in the abuse command.

2021-03-10 13:59 UTC, ozkatz commented on cmd/lakectl/cmd/abuse.go
> +				add(fmt.Sprintf("%sfile-%d", prefix, i))
I don't want, it might do "\" if my client happens to run on windows :(

2021-03-10 15:54 UTC, ozkatz commented on cmd/lakectl/cmd/abuse.go
> +		u := uri.Must(uri.Parse(args[0]))
true but we can't tell before actually asking lakeFS. this will result in errors which I think is fine.

2021-03-10 15:55 UTC, ozkatz commented on cmd/lakectl/cmd/abuse.go
> +			client := getClient()
yes, it comes with its own TCP connection caching

2021-03-10 15:59 UTC, ozkatz commented on docs/architecture/sizing-guide.md
> +committing 100 changes will take roughly the same amount of time whether the resulting commit contains 500 or 500 million objects.
yes because it is not constant, its O(changeset)

2021-03-10 16:01 UTC, ozkatz commented on docs/architecture/sizing-guide.md
> +This test generates random read requests to lakeFS,
OTOH the input file I used is relatively small, so it will generate many requests to the same set of (overwhelmingly likely) cached sstables.

2021-03-10 16:33 UTC, itaiad200 commented on docs/architecture/sizing-guide.md
> +committing 100 changes will take roughly the same amount of time whether the resulting commit contains 500 or 500 million objects.
Yeah, I mean for those 100 objects that changed (or 1k, 10k, ...)

2021-03-10 16:35 UTC, itaiad200 approved these changes
LGTM!
Left a minor suggestion to add timing for the commit operation, even if it depends only on the number of changes ( <1m is a nice number too :) )

2021-03-11 09:04 UTC, merged

2021-03-11 11:38 UTC, arielshaqed approved these changes
Very (very!) neat stuff!

2021-03-11 11:38 UTC, arielshaqed commented on docs/architecture/sizing-guide.md
> +that would require about 3 GiB of RAM.
nit: close bracket

2021-03-11 11:38 UTC, arielshaqed commented on docs/architecture/sizing-guide.md
> +PostgreSQL CPU cores help scale concurrent requests. Ideally 1 CPU core for every 5,000 requests/second is ideal.
```suggestion
PostgreSQL CPU cores help scale concurrent requests. 1 CPU core for every 5,000 requests/second is ideal.
```

2021-03-11 11:38 UTC, arielshaqed commented on docs/architecture/sizing-guide.md
> +Scaling lakeFS, like most data systems, moves across 2 axis:
nit:
```suggestion
Scaling lakeFS, like most data systems, moves across 2 axes: 
```

2021-03-11 11:38 UTC, arielshaqed commented on docs/architecture/sizing-guide.md
> +concurrency (throughput of requests at a given timeframe), and latency (time to complete a single request).
Not sure of this usage of "concurrency"; I usually don't use it as a measure of throughput.

2021-03-11 11:38 UTC, arielshaqed commented on docs/architecture/sizing-guide.md
> +Historgram (ms):
nit:
```suggestion
Histogram (ms):
```

2021-03-11 11:38 UTC, arielshaqed commented on docs/architecture/sizing-guide.md
> +## Reference architectures
In future I would split this off into another page.