Check context during apply, diff and merge loops
treeverse/lakeFS pull request #1603
Opened 2021-03-10 10:31 UTC by nopcoder

Fix #1598

2021-03-10 11:43 UTC, ozkatz requested changes
Looks great overall, but these changes come with no test coverage so kind of hard to validate correctness (now and in future changes).

2021-03-10 11:43 UTC, ozkatz commented on graveler/committed/apply.go
> +			return ret, ctx.Err()
How was this tested? (question applies to all other places where this type of check has been introduced..)

2021-03-10 11:43 UTC, ozkatz commented on graveler/committed/apply.go
> +			return 0, ctx.Err()
How was this tested?

2021-03-10 15:36 UTC, nopcoder commented on graveler/committed/apply.go
> +			return 0, ctx.Err()
added test code

2021-03-10 16:26 UTC, ozkatz approved these changes
Looks great!

2021-03-10 21:07 UTC, merged

2021-03-30 14:47 UTC, arielshaqed commented
As part of reviewing #1652, I discovered that I don't understand this PR.  It seems like polling for context cancellation throughout work that is not CPU intensive.  I would *expect* the iterators to receive context and pipe it through to some RocksDB SSTable iterator, which would handle it at some stage.

If the SSTable RocksDB iterators _don't_ handle cancellation (maybe because they cannot pipe it through to IO, because of the whole Go IO / os.File no-context fiasco), then I would expect to handle this at the iterator level.

Handling it here in `Apply` means that we cannot make use of some hypothetical better underlying iterator in the future, and also that every operation that does _not_ use `Apply` cannot be cancelled.

2021-03-30 15:14 UTC, nopcoder commented
It does polling the context for cancelation in order to support cancellation regardless of the iterator's implementation.

Why the extra check prevents better underlying interator? the iterator can cancel by context if needed. The concern, for example, is if you wrap the implementation with a cache that will iterator the data from memory without calling any underlying API that will check the content.

We can assign the responsibility of context cancellation on the underlying but need to verify in some way that all iterators either check the context or call an API that does that.