Support multiple gateway domain names
treeverse/lakeFS pull request #1720
Opened 2021-04-05 20:29 UTC by arielshaqed

Remaining issues:
1. Middleware EnrichWithOperation always takes first domain.  Can we take req.Host?  (If not, at
   make sure to allow *zero* domains)
2. sigV2 implementation uses the *configured* "bare domain" to sign.  This is sort-of quite a
   lot like using req.Host (but not entirely).

Fixes #1719.

2021-04-18 12:29 UTC, arielshaqed commented
Tested host-style addressing *manually* using Postman:
1. Recorded a request.
2. Configured lakeFS to accept *both* domains.
2. Added DNS records for `puddle.lakefs.io`, `*.puddle.lakefs.io` to point at 127.0.0.1 (just like `local.lakefs.io` and `*.local.lakefs.io` do).
2. Set "AWS Signature" in Authorization with my AccessKey [ID...] and Secret [Access] Key, the region, and service name "s3".
3. Changed "Host" header to other domain name.
4. Changed DNS in GET (not really needed)
5. Removed bucket from GET URL.

It worked, proving host-based addressing works.

2021-04-18 13:17 UTC, arielshaqed commented
Opened #1769, #1770 for missing test automation.

2021-04-18 15:44 UTC, guy-har requested changes
Looks Great, 
some bugs might occur in case one bare domain is a prefix of another.
I think we should extract the relevant bare domain for each case, that should also help out with `sigV2` and `FQDN`

2021-04-18 15:44 UTC, guy-har commented on pkg/config/config.go
> +	GatewaysS3DomainNamesKey = "gateways.s3.domain_name"
```suggestion
	GatewaysS3DomainNamesKey = "gateways.s3.domain_names"
```

2021-04-18 15:44 UTC, guy-har commented on pkg/config/template.go
> +			DomainNames Strings `mapstructure:"domain_name"`
```suggestion
			DomainNames Strings `mapstructure:"domain_names"`
```

2021-04-18 15:44 UTC, guy-har commented on pkg/config/template.go
> +type Strings []string
Nice 😎

2021-04-19 09:07 UTC, guy-har approved these changes
LGTM
one small comment.

2021-04-19 09:07 UTC, guy-har commented on pkg/gateway/middleware.go
> +		if strings.HasSuffix(hostname, "." + bd) {
what about `bd == hostname`?

2021-04-19 09:08 UTC, guy-har commented
Adding here documentation related to sigV2 and FQDN
`https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html`
`https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html`

2021-04-19 13:12 UTC, guy-har commented on pkg/gateway/middleware.go
> +			}
👍

2021-04-19 14:05 UTC, arielshaqed reviewed
Thanks; handled all things written down and/or discussed.  Changes should be nicely organized by commit, so easiest to review by individual commit.

2021-04-19 15:43 UTC, arielshaqed commented
Thanks!

Pulling once tests pass...

2021-04-19 16:25 UTC, merged