Feature/lakectl internal paging
treeverse/lakeFS pull request #1759
Opened 2021-04-13 10:39 UTC by johnnyaug

2021-04-16 19:10 UTC, nopcoder requested changes

2021-04-16 19:10 UTC, nopcoder commented on cmd/lakectl/cmd/repo.go
> +	repoListCmd.Flags().Int("amount", 100, "number of results to return")
constant. relevant to all the places in this change.

2021-04-16 19:10 UTC, nopcoder commented on pkg/actions/db_task_result_iterator.go
> +		Where(sq.Gt{"hook_run_id": it.offset}).
good catch - I need to a test for this one

2021-04-16 19:10 UTC, nopcoder commented on pkg/auth/service.go
> +			ORDER BY auth_users.display_name
how this one worked so far

2021-04-18 11:53 UTC, johnnyaug commented on pkg/auth/service.go
> +			ORDER BY auth_users.display_name
it didn't :)

2021-04-19 06:51 UTC, nopcoder commented on pkg/auth/service.go
> +				AND auth_users.display_name like $3
why listing needs to filter by prefix? we use this one as `after` which means you should get something that doesn't match the value's prefix.

2021-04-19 08:04 UTC, nopcoder commented on pkg/auth/service.go
> +				AND auth_users.display_name like $3
All good - didn't saw it is prefix.

2021-04-19 08:04 UTC, nopcoder approved these changes

2021-04-19 08:12 UTC, merged