api authorization jwt check the standard way
treeverse/lakeFS pull request #1832
Opened 2021-04-28 17:07 UTC by nopcoder

Closes #1362

2021-04-29 06:17 UTC, arielshaqed requested changes
Whitespace changes requested :-(

2021-04-29 07:26 UTC, nopcoder commented on pkg/api/auth_middleware.go
> +				if len(parts) != 2 || !strings.EqualFold(parts[0], "Bearer") {
switched to use Fields instead of Split

2021-04-29 10:20 UTC, arielshaqed approved these changes
Thanks!

This is OK in practice, and sorta OK in theory: the Bearer token has a fixed format, and does not allow spaces.  But in a perfect world I'd probably match `/^Bearer\s+(.*)$/' and take $1.

2021-05-02 06:44 UTC, nopcoder commented
> Thanks!
> 
> This is OK in practice, and sorta OK in theory: the Bearer token has a fixed format, and does not allow spaces. But in a perfect world I'd probably match `/^Bearer\s+(.*)$/' and take $1.

Totally agree.  If you think it is will be more readable as a regular expression pattern I can update the implementation.

2021-05-02 06:44 UTC, merged