Test lakeFS with direct-access "thick" Spark client
treeverse/lakeFS pull request #1924
Opened 2021-05-09 11:15 UTC by arielshaqed

Fixes #1921.

2021-05-11 06:13 UTC, arielshaqed commented
Note that test still doesn't _pass_.  Pulling it allows people to work on the many ways it can fail, as well as keep sync'ed on progress and separate fixes into multiple PRs.

2021-05-11 09:53 UTC, nopcoder requested changes

2021-05-11 09:53 UTC, nopcoder commented on test/spark/run-test.sh
> +export output="lakefs://${REPO}/main/sonnets-wordcount.csv"
why do we need these as exported env variables - can we just pass the values without defining env variable for each data we pass?

2021-05-11 09:53 UTC, nopcoder commented on test/spark/docker-compose.yaml
> +      - s3output
if possible I prefer not to pass these and env - it should of the command we execute part of the command we run.

2021-05-11 09:53 UTC, nopcoder commented on .github/workflows/nessie.yaml
> +                                # containers!
why do we need to import - spark-submit doesn't copy the jar for us?

2021-05-11 09:54 UTC, nopcoder commented
A question and request to remove the extra environment variables (input/output) from the game.

2021-05-12 12:00 UTC, nopcoder approved these changes

2021-05-13 09:25 UTC, arielshaqed commented
Thanks!

2021-05-13 09:25 UTC, merged