Auth System Tests (#657)
treeverse/lakeFS pull request #2101
Opened 2021-06-11 06:55 UTC by adunuthulan

Fixes #657 

Created system tests using different clients, each with the policies of the user groups Developers, SuperUsers, and Viewers. Each test checks to see if the client correctly responds to the user's assigned policies. I plan on adding merging to the set of tests.

2021-06-11 10:06 UTC, itaiad200 requested changes
Really enjoyed reviewing this code, it is clean, concise and well-documented. The PR description is also very helpful in understanding where this stands.

Feel free to undraft for next iteration after fixing the comments and adding the tests that you wrote.

2021-06-11 10:06 UTC, itaiad200 commented on nessie/auth_test.go
> +	require.Equal(t, http.StatusNoContent, resDelRep.StatusCode(), "SuperUser unexpectedly did not receive no content response while deleting repo")
The admin can do so much more, like managing groups. Let's add more checks for those as well.

2021-06-15 08:55 UTC, itaiad200 approved these changes
Thanks for fixing the comments. Approved

2021-06-15 17:07 UTC, merged

2021-06-16 07:16 UTC, arielshaqed reviewed
Thanks for testing a really important part of the system!  This is a really good test.

I am asking for some refactoring it to a more data-driven style.  That is the Go Way, but more importantly I believe that it has significant advantages here in making it easier to review and maintain the code.

# There is :snail:  *NO URGENCY* :snail: in doing this!  The repo is better with this test than without it!

If you like I'd be very happy to go over how we might improve maintainability here.  Let me know :-)

Thanks!

2021-06-16 07:16 UTC, arielshaqed commented on pkg/testutil/setup.go
> +	endpointURL := ParseEndpointURL(logger, viper.GetString("endpoint_url"))
Hurrah! :confetti_ball: