Fix LakeFS startup with Azure storage type
treeverse/lakeFS pull request #2250
Opened 2021-07-16 12:40 UTC by evelkey

LakeFS is not able to start after a restart if using Azure Blob storage as it returns `https` as storage class and lakeFS uses `azure` as storage class. This is fixed by an extended check for exactly this case by this PR.

2021-07-16 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2250) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2250) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=2250) it.</sub>

2021-07-16 13:45 UTC, arielshaqed commented
Hi @evelkey,
Thanks for the PR! I've gone ahead and assigned either of the people who know most about Azure urls to review. Please bear in mind that it's already weekend here so we may manage to review it only on Sunday.
 In the meantime I've kicked off our ci process on this PR.

2021-07-16 14:02 UTC, nopcoder commented
You can pass the flag -m that will skip this check at startup, until this issue will be resolved.

2021-07-18 07:27 UTC, guy-har requested changes
Thanks for contributing, 
I prefer not to handle this as a special case, Separating the `StorageType.String()` method into two methods, one for returning the
storage type and one for returning the default schema could do the job.
I also noticed There is another validation in `LinkPhysicalAddress` in `controller.go`
that will also fail now.

2021-07-18 10:23 UTC, guy-har approved these changes
@evelkey Thanks for finding and resolving this issue!
Due to the importance of this issue, in order to publish a fix ASAP, I Approve.
Opening an issue so the change request will be resolved in an additional PR.

2021-07-18 10:39 UTC, evelkey commented
Thank you @guy-har, we tested it in our AKS deployment with Azure blob as the backend storage (needed to migrate from version 30 to 31) and all used features are now functional again.

2021-07-18 14:31 UTC, merged