Update to github.css
treeverse/lakeFS pull request #2279
Opened 2021-07-23 08:44 UTC by JamilAhmad

Jamil Dev

2021-07-23 08:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2279) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2279) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=2279) it.</sub>

2021-07-23 08:46 UTC, arielshaqed requested changes
Thanks for your submission! In accordance with many css style guides we do not allow overrides without a comment explaining why for future maintainers.

2021-07-26 07:07 UTC, nopcoder commented
Hi @JamilAhmad I've created https://github.com/treeverse/lakeFS/pull/2284 it is just a draft and not a final work on how the custom style can be applied without modifying github.css.
I don't have enough knowledge to sync everything you applied into it - there are missing parts in the 'toc' and 'code' which I will need more time to apply, but I'm sure for you it will go smoother.

Also, there is more information on how to customize the theme we use here https://github.com/pmarsceill/just-the-docs/blob/master/docs/customization.md

2021-08-01 11:58 UTC, nopcoder commented
Please include this change with the new pull request that handles the consumerization using custom.scss

2021-08-01 11:58 UTC, closed without merging