Add Airflow hook documentation
treeverse/lakeFS pull request #2291
Opened 2021-07-26 14:47 UTC by itaiad200

closes #2283

2021-07-26 14:59 UTC, johnnyaug requested changes

2021-07-26 14:59 UTC, johnnyaug commented on docs/setup/hooks.md
> +Ends successfully if the DAG was triggered, and fails if it wasn't.
```suggestion
The hook run succeeds if the DAG was triggered, and fails otherwise.
```

2021-07-26 14:59 UTC, johnnyaug commented on docs/setup/hooks.md
> +| url      | The URL address of the Airflow instance         | String    | "http://localhost:8080" | true     |
```suggestion
| url      | The URL of the Airflow instance         | String    | "http://localhost:8080" | true     |
```

2021-07-26 14:59 UTC, johnnyaug commented on docs/setup/hooks.md
> +| username | The name of the user performing the request     | String    | "admin"                 | true     |
Which user is it? Airflow?

2021-07-26 14:59 UTC, johnnyaug commented on docs/setup/hooks.md
> +| conf     | DAG run configuration that will be pass as is   | JSON      |                         | false    |
```suggestion
| conf     | DAG run configuration that will be passed as is   | JSON      |                         | false    |
```

2021-07-26 14:59 UTC, johnnyaug commented on docs/setup/hooks.md
> +The key of the record would be `lakeFS_event` and value will match the one described in the previous [schema](#request-body-schema)
```suggestion
The key of the record will be `lakeFS_event` and the value will match the one described [here](#request-body-schema)
```

2021-07-26 14:59 UTC, johnnyaug commented on docs/setup/hooks.md
> +lakeFS will add an entry to the configuration property with the event that triggered the action.
Which configuration?

2021-07-27 07:19 UTC, nopcoder approved these changes

2021-07-27 07:19 UTC, nopcoder commented on docs/setup/hooks.md
> +#### Hook Record in configuration field
DAG conf

2021-07-27 07:35 UTC, itaiad200 commented on docs/setup/hooks.md
> +| username | The name of the user performing the request     | String    | "admin"                 | true     |
Yes. Done.

2021-07-27 07:35 UTC, itaiad200 commented on docs/setup/hooks.md
> +lakeFS will add an entry to the configuration property with the event that triggered the action.
Airflow request, added.

2021-07-27 07:57 UTC, johnnyaug approved these changes

2021-07-27 07:58 UTC, merged