Update to custom.scss
treeverse/lakeFS pull request #2314
Opened 2021-08-02 02:02 UTC by JamilAhmad

I have updated the custom.scss file according to the theme documentation and implemented the new zeplin design changes properly hope things will be good now, please review and let me know if any question

2021-08-02 02:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2314) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2314) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=2314) it.</sub>

2021-08-02 09:24 UTC, nopcoder requested changes
wrote a couple of comments in the pull request body.
as part of customizing the default theme, I would try to reduce the use of  `!important` as must as possible.

2021-08-02 09:24 UTC, nopcoder commented on docs/_sass/custom/custom.scss
> +/*overridden*/
The next part doesn't look like scss - example I found: https://gist.github.com/akullpp/6375168d0400ee2e7e3a93820d94ba54

2021-08-05 11:08 UTC, nopcoder requested changes
1. can you address the open question I left as comment?
2. please remove the overrides we pushed into the github.css and see that these changes apply without them?

2021-08-05 14:57 UTC, JamilAhmad reviewed
All done

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +	src: local(Rene-Bieder-Galano-Grotesque-Medium),
Fixed name of the font and changed it to Galano-Grotesque-Medium

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +$lightblack:#6e7171;
Removed All repetition

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +$darkgrey:#949494;
Removed All repetition

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +			background-color: $whitegrey;
Removed one, now its only one background property

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +		font-size: 42px!important;
Fixed formate

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +		font-size: 18px!important;
Removed important where not needed

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +				/* padding: 8px 0; */
Comments removed

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +    	border: 0px solid #d8faf1;
Fixed

2021-08-05 14:57 UTC, JamilAhmad commented on docs/_sass/custom/custom.scss
> +		/* background-color: initial; */
Removed

2021-08-06 14:11 UTC, nopcoder commented
> All done

please remove the overrides we pushed into the github.css and see that these changes apply without them?

2021-08-08 16:01 UTC, nopcoder approved these changes

2021-08-08 16:49 UTC, merged