Add python client documentation
treeverse/lakeFS pull request #2337
Opened 2021-08-09 12:39 UTC by guy-har

This PR:
1. Changes the docker image used to create the python client to support Jekyll which was done on [this](https://github.com/treeverse/openapi-generator/tree/v5.1.0.1) forked version of openapi-generator
2. Adds an action that commits and pushes the new version to https://github.com/treeverse/docs-lakefs-python
3. Adds a reference to the python documentation in our lakeFS documentation

2021-08-09 14:02 UTC, guy-har commented
closes #2136

2021-08-09 14:06 UTC, johnnyaug requested changes

2021-08-09 14:06 UTC, johnnyaug commented on clients/python/Gemfile
> +gem 'github-pages', group: :jekyll_plugins
Please add Gemfile, Gemfile.lock  and _config.yml to `.gitattributes` with `linguist-generated=false`.
This way they will appear normally in the diff.
While you're at it, also  lakefs_client/client.py :)

2021-08-09 14:14 UTC, guy-har commented on docs/integrations/python.md
> +For the documentation of lakeFS’s python package, see [https://pydocs.lakefs.io](https://pydocs.lakefs.io)
I Considered that but Given that the python docs are automatically generated, I prefer that readers will go through our documentation before. WDYT?

2021-08-10 08:03 UTC, guy-har commented on .github/workflows/pypi.yaml
> +      run: bundle exec jekyll build -d _site/${{ steps.docver.outputs.tag }} -b /${{ steps.docver.outputs.tag }}
Nice :) 
Added

2021-08-10 09:02 UTC, johnnyaug commented on clients/.gitattributes
> +python/_config.yml linguist-generated=false
add newline

2021-08-10 09:02 UTC, johnnyaug approved these changes
Nice!!

2021-08-10 14:35 UTC, merged