Define and detect missing required config keys
treeverse/lakeFS pull request #2377
Opened 2021-08-16 11:24 UTC by arielshaqed

Fixes #2363.

2021-08-16 14:41 UTC, arielshaqed commented
This will probably conflict with #2370, make sure to rebase to `master` HEAD before merging.

2021-08-16 15:18 UTC, arielshaqed commented
Ready for review! :-)

1. Passes all its tests.
2. Tested manually with and without required fields.
3. Scanned docs and reference to see that we have no config files without the required fields.
4. https://compose.lakefs.io also includes the required fields.
5. treeverse/charts#86 makes it work with our Helm chart, and I tested that that loads by pushing my own Docker image and running the test.  But please review that one too!

2021-08-17 06:39 UTC, nopcoder approved these changes
Did you consider a method IsValid to Config that will check if the required field is not empty or just return the list of missing required fields?
Unless you think we will require more fields in the future - think it is a bit complex or too generic (if there is such thing)

2021-08-17 07:22 UTC, arielshaqed commented
Thanks!

>  Unless you think we will require more fields in the future - think it is a bit complex or too generic (if there is such thing)

I think that we will have more fields in future.  The actual checking code is surprisingly fragile to write by hand, particularly when pointers are present.  That's when you begin to feel the missing `.?` operator of ECMAScript.  And I think that we should use it in `lakectl` config as well.

I did write some fairly extensive tests, in order to increase confidence.

Also I want `template.go` to be the single source of truth for configuration.  Consider e.g. wanting to generate the list of configuration keys automatically.

Still waiting on treeverse/charts#86.

2021-08-17 08:29 UTC, nopcoder commented on pkg/config/config.go
> +	missingKeys := GetMissingRequiredKeys(c.values, "mapstructure", "squash", "required")
consider using "verify" or other tag names that will hold "required" as value, later we can add more constraints.

2021-08-17 09:08 UTC, johnnyaug requested changes

2021-08-17 09:08 UTC, johnnyaug commented on pkg/config/struct_keys.go
> +func appendStructKeysIfZero(value reflect.Value, typ reflect.Type, tag, squashValue, requiredTag string, prefix []string, keys []string) []string {
This function is very hard to read. Can you please add some comments?

2021-08-17 15:29 UTC, arielshaqed reviewed
Thanks; PTAL!

2021-08-17 15:29 UTC, arielshaqed commented on pkg/config/config.go
> +func NewConfigIncompleteForTesting() (*Config, error) {
Did (1)!

2021-08-18 08:27 UTC, johnnyaug approved these changes

2021-08-19 09:00 UTC, arielshaqed commented
Thanks!  Fixed merge conflicts, waiting for tests and then pushing...

2021-08-19 09:16 UTC, merged