Fix "checking repositories for mismatched adapter"
treeverse/lakeFS pull request #2381
Opened 2021-08-17 08:04 UTC by arielshaqed

Was unformatted, looking like
```
DEBUG  [2021-08-17T11:01:54+03:00]cmd/lakefs/cmd/run.go:213 cmd/lakefs/cmd.checkForeignRepos lakeFS is initialized, checking repositories for mismatched adapter(%s)s3 
```

2021-08-18 07:51 UTC, johnnyaug requested changes

2021-08-18 07:51 UTC, johnnyaug commented on cmd/lakefs/cmd/run.go
> +		logger.Debugf("lakeFS is initialized, checking repositories for mismatched adapter(%s)", blockStore.BlockstoreType())
```suggestion
		logger.WithField("adpater", blockStore.BlockstoreType()).Debug("lakeFS is initialized, checking repositories for mismatched adapter")
```

2021-08-23 08:40 UTC, arielshaqed commented on cmd/lakefs/cmd/run.go
> +		logger.Debugf("lakeFS is initialized, checking repositories for mismatched adapter(%s)", blockStore.BlockstoreType())
Done!  PTAL...

2021-08-24 08:51 UTC, johnnyaug approved these changes
Sorry for the delay

2021-08-24 09:17 UTC, merged