Bugfix/2307 change error message in lakefs setup
treeverse/lakeFS pull request #2435
Opened 2021-09-01 16:35 UTC by lynnro314

2021-09-01 16:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2435) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=2435) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=2435) it.</sub>

2021-09-01 18:40 UTC, nopcoder requested changes
Looks good, just think we need to use the same terminology - setup and not initialized and drop the lakeFS.

2021-09-02 05:55 UTC, talSofer reviewed
Nice!

Please edit the following to the pr description:
1. Fixes #2307 (this automatically closes the issue when you merge the pr)
2. fix description. What was the problem, and what solution you implemented.

2021-09-02 06:06 UTC, talSofer commented
> Looks good, just think we need to use the same terminology - setup and not initialized and drop the lakeFS.

Agree with @nopcoder . To understand if setup already happened you are checking whether the metadata manager is already initialized which is an implementation detail. as a user I would want the software to speak the language of the actions I'm taking.

2021-09-05 08:42 UTC, nopcoder requested changes

2021-09-05 08:42 UTC, nopcoder commented on cmd/lakefs/cmd/setup.go
> +			fmt.Printf("Setup is already complete.")
Add new-line or use fmt.Println

2021-09-05 09:15 UTC, nopcoder approved these changes

2021-09-12 12:57 UTC, merged