Support s3 api copy-object across repositories
treeverse/lakeFS pull request #2575
Opened 2021-10-19 18:46 UTC by eden-ohana

Fixes #2162 

Currently supports copy-object only for the same repository.

2021-10-31 13:14 UTC, guy-har requested changes
Grew out to be a very valuable PR,
Great Job!
Some minor requests. requesting changes mainly because of the panic returned in the default case.

2021-10-31 13:14 UTC, guy-har commented on pkg/gateway/operations/putobject.go
> +func extractAndCopyEntryFromCopyReq(w http.ResponseWriter, req *http.Request, o *PathOperation, copySource string) *catalog.DBEntry {
Doesn't really extract, this is basically a copy command that returning, please change name and documentation to reflect that

2021-10-31 13:14 UTC, guy-har commented on pkg/gateway/operations/putobject.go
> +// extractEntryFromCopyReq: update metadata to refer to the source hash in the destination workspace
What is updated?

2021-10-31 13:29 UTC, guy-har commented
Not part of this PR, but maybe we should open a new Issue for adding copy to our API, we already have the capability. WDYT?

2021-10-31 13:53 UTC, eden-ohana commented on pkg/gateway/operations/putobject.go
> +// extractEntryFromCopyReq: update metadata to refer to the source hash in the destination workspace
I divided it into two functions

2021-11-02 17:19 UTC, guy-har approved these changes
Approved :)
Please remove or change the documentation I commented about.

2021-11-02 17:19 UTC, guy-har commented on nessie/s3_gateway_test.go
> +		t.Errorf("download %s: %s", o.DestPath, err)
```suggestion
		t.Fatal("download %s: %s", o.DestPath, err)
```
You could use Fatal in cases of errors where you don't want your test to continue running

2021-11-02 17:27 UTC, guy-har commented on nessie/s3_gateway_test.go
> +	sourceObjectStats := resp.JSON200
```suggestion
	require.Equal(t, http.StatusOK, resp.StatusCode())
	sourceObjectStats := resp.JSON200
```

2021-11-02 17:33 UTC, guy-har commented on nessie/s3_gateway_test.go
> +	}
```suggestion

	Content:=    testutil.RandomString(rand, randomDataContentLength)
	SourcePath:= prefix + "source-file"
	DestPath: =  prefix + "dest-file"

```

2021-11-02 17:36 UTC, guy-har commented on nessie/s3_gateway_test.go
> +	}
You don't really need the Object type, also it's a bit confusing that the Object has two paths

2021-11-04 06:52 UTC, merged