2629 hadoop cli
treeverse/lakeFS pull request #2702
Opened 2021-11-14 11:02 UTC by itaiad200

Fixes #2629 

`globStatus` method wasn't used by any other prior tool we used to check the lakeFS Hadoop Filesystem. It had to be implemented since hadoop cli is using it. The incoming `globPattern` param is just a prefix in all flows. Not sure if we'll ever need to support a real glob pattern.

2021-11-15 07:28 UTC, arielshaqed requested changes
1. How was this tested?

1. Does it would with [`count`](https://hadoop.apache.org/docs/r2.4.1/hadoop-project-dist/hadoop-common/FileSystemShell.html#count)?

1. Does the Hadoop FS spec test include something to test for this?  If so then we should ensure that it runs.

1. I don't understand how this implements [`globStatus`](https://hadoop.apache.org/docs/r2.7.1/api/org/apache/hadoop/fs/FileSystem.html#globStatus(org.apache.hadoop.fs.Path)) (and indeed IIUC the comment on the PR says that it does not).  If we provide only partial support, then I guess we would need to throw some "not implemented" exception when `path` contains any wildcards, rather than return an incorrect answer.

2021-11-15 07:28 UTC, arielshaqed commented on clients/hadoopfs/src/main/java/io/lakefs/LakeFSFileSystem.java
> +        try{
nit:
```suggestion
        try {
```

2021-11-15 13:55 UTC, nopcoder reviewed
Looking at 2.7.x s3a implementation - https://github.com/apache/hadoop/blob/release-2.7.1/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java it doesn't override this method.
Looking at the base implementation https://github.com/apache/hadoop/blob/release-2.7.1/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L1654
It uses a Globber implementation https://github.com/apache/hadoop/blob/release-2.7.1/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/Globber.java that calls the fs implementation to support the functionality.
Can you identify why the base implementation doesn't work for us? maybe there is a missing API or missed returning some data that will enable us this functionality?

2021-11-21 10:14 UTC, itaiad200 commented on clients/hadoopfs/src/main/java/io/lakefs/LakeFSFileSystem.java
> +        try{
Code deleted.

2021-11-21 10:18 UTC, itaiad200 commented
Following @nopcoder & @arielshaqed advices, I checked again the base implementation.

What I assumed didn't work before, is actually in parity with the s3a behaviour. Therefore implementing the `globPattern` method is not needed and it's ok to rely on the basic implementation that will make the appropriate FS calls.

Was tested using FileSystemTracer that compares the behaviour of s3a and lakeFS FS with the Hadoop CLI which was the tool that initiated this bug (no other tool is calling the `globPattern`).

2021-11-21 11:55 UTC, arielshaqed approved these changes
This looks exactly right, only it remains untested.  I am approving as it is clearly better than what we have.  But I would be **really** happy if you could find & enable some test in the spec, and/or add a test of our own.

Thanks!

2021-11-21 13:53 UTC, merged