Use aws sdk go v2
treeverse/lakeFS pull request #2717
Opened 2021-11-17 13:20 UTC by arielshaqed

Advantages:
1. Long-term support.
1. (Somewhat) cleaner semantics.
1. Allows context-logging -- add lakeFS request ID to AWS logs.  (That's impossible in `aws-sdk-go` with the `v2`...).

Does _not_ migrate the CLIs, including especially `lakectl metastore`.

2021-11-21 08:32 UTC, arielshaqed commented
**Releaser**: Please _do_ mention this in changelog, e.g.:
> Use version 2 of the AWS Go SDK.  This should have no user-visible consequences, but is a large change.

2021-11-21 14:53 UTC, arielshaqed commented
So... ready-ish for review in the sense that it all works.

BUT 88ebedd should really not be pulled without many tests, which is #2732.  Keeping as "**DRAFT**" so as not to pull it.

2021-11-22 09:59 UTC, nopcoder requested changes

2021-11-22 09:59 UTC, nopcoder commented on pkg/logging/aws.go
> +func (l *AWSAdapter) logFunc(cls aws_logging.Classification) func(...interface{}) {
Guess we need to wire this one to the adapter's cache creation and have the s3 client use it.

2021-11-22 09:59 UTC, nopcoder commented on pkg/testutil/db.go
> +			})
```suggestion
		configLoadOpts = append(configLoadOpts, aws_config.WithLogConfigurationWarnings(true))
```

too bad that they had a type function type and didn't use it for the setup - LoadOptionsFunc

2021-11-22 09:59 UTC, nopcoder commented on pkg/testutil/db.go
> +			// TODO(ariels)...
?

2021-11-22 09:59 UTC, nopcoder commented on pkg/cloud/aws/s3inventory/utils_test.go
> +		},
```suggestion
		aws_config.WithRegion("eu-central-1"),
```

2021-11-22 09:59 UTC, nopcoder commented on pkg/testutil/setup.go
> +		},
```suggestion
			aws_config.WithRegion("us-east-1"),
			aws_config.WithLogConfigurationWarnings(true),
```

2021-11-24 13:26 UTC, arielshaqed reviewed
Thanks!

2023-04-28 06:26 UTC, closed without merging