Fix naming in apply
treeverse/lakeFS pull request #2837
Opened 2021-12-27 13:10 UTC by johnnyaug

We use confusing terms in the applier:
* We call the commit on which we apply the changes _source_ This is confusing since it's not really a source of anything, and typically in a merge operation this would the merge _destination_. Suggested new name: _base_ (since "base" is also a term in the merge operation this may not be the best name, so I'm open to other suggestions).
* We call the iterator containing the changes _diffs_ - but these are not diffs, these are only the new values and they are not similar to other diffs in our code. Suggested new name: _changes_.

2021-12-27 13:22 UTC, guy-har requested changes
There are still some `source` and `diff`.  please verify that we change them all, otherwise it would be even more confusing

2021-12-27 13:22 UTC, guy-har commented on pkg/graveler/committed/apply.go
> +func (a *applier) applySourceRangeChangeKey(baseRange *Range, changeValue *graveler.ValueRecord) error {
```suggestion
func (a *applier) applyBaseRangeChangeKey(baseRange *Range, changeValue *graveler.ValueRecord) error {
```

2021-12-27 13:22 UTC, guy-har commented on pkg/graveler/committed/apply.go
> +func (a *applier) applyChangeRangeSourceKey(changeRange *Range, baseValue *graveler.ValueRecord) error {
```suggestion
func (a *applier) applyChangeRangeBaseKey(changeRange *Range, baseValue *graveler.ValueRecord) error {
```

2021-12-27 13:22 UTC, guy-har commented on pkg/graveler/committed/apply.go
> +		a.haveSource = a.base.Next()
```suggestion
		a.haveBase = a.base.Next()
```

2021-12-27 13:22 UTC, guy-har commented on pkg/graveler/committed/apply.go
> +		a.haveSource = a.base.NextRange()
```suggestion
		a.haveBase = a.base.NextRange()
```

2021-12-27 13:22 UTC, guy-har commented on pkg/graveler/committed/apply_test.go
> +func TestSourceRangesWithinChangeRange(t *testing.T) {
```suggestion
func TestBaseRangesWithinChangeRange(t *testing.T) {
```

2021-12-27 13:22 UTC, guy-har commented on pkg/graveler/committed/apply.go
> +	haveChanges, haveSource bool
```suggestion
	haveChanges, haveBase bool
```

2021-12-27 13:24 UTC, guy-har commented
This is a great idea and will make the code easier to follow,
Thanks, Yoni!

I think that `changes` is perfect
`base` is better than `source`, but still not optimal.

2021-12-27 18:56 UTC, nopcoder commented
Great change @johnnyaug - love it.

2021-12-28 08:15 UTC, eden-ohana reviewed
Great change! Maybe consider origin instead of base.

2021-12-28 11:54 UTC, johnnyaug commented
After discussing with everyone f2f, I've decided to merge as-is, considering that:
1. all suggested names are problematic
2. a refactor is anyway expected in this area

2021-12-28 11:58 UTC, eden-ohana approved these changes

2021-12-28 11:58 UTC, guy-har approved these changes

2021-12-28 12:01 UTC, merged