Larger staging listing batch size for commit
treeverse/lakeFS pull request #2888
Opened 2022-01-25 15:31 UTC by guy-har

2022-01-25 18:10 UTC, nopcoder requested changes
If all is internal, I prefer to pass the constant with the value. the iterator can handle 0 and -1 in case of user input.

2022-01-26 11:12 UTC, nopcoder commented on pkg/graveler/staging/iterator.go
> +	if bs > graveler.ListingMaxBatchSize {
else if

2022-01-26 11:13 UTC, nopcoder approved these changes
LGTM

2022-01-26 11:50 UTC, itaiad200 commented on pkg/graveler/staging/iterator.go
> +func NewStagingIterator(ctx context.Context, db db.Database, log logging.Logger, st graveler.StagingToken, bachSize int) *Iterator {
```suggestion
func NewStagingIterator(ctx context.Context, db db.Database, log logging.Logger, st graveler.StagingToken, batchSize int) *Iterator {
```

2022-01-26 11:59 UTC, guy-har commented on pkg/graveler/staging/iterator.go
> +func NewStagingIterator(ctx context.Context, db db.Database, log logging.Logger, st graveler.StagingToken, bachSize int) *Iterator {
Thanks!

2022-01-26 12:24 UTC, merged