Add example for `lakectl tag create` command
treeverse/lakeFS pull request #2902
Opened 2022-02-02 14:49 UTC by mishraprafful

**Related Issues**
Partially addresses #2409

**Introduced Changes**
Added an example for `lakectl tag crate` command

2022-02-06 08:51 UTC, johnnyaug requested changes
Thank you for your PR, @mishraprafful, this is great. A small correction to conform with our other docs.

2022-02-06 08:51 UTC, johnnyaug commented on cmd/lakectl/cmd/tag.go
> +	Example: "lakectl tag create lakefs://some-repo-name/some-tag-name 2397cc9a9d04c20a4e5739b42c1dd3d8ba655c0b3a3b974850895a13d8bf9917",
```suggestion
	Example: "lakectl tag create lakefs://example-repo/example-tag 2397cc9a9d04c20a4e5739b42c1dd3d8ba655c0b3a3b974850895a13d8bf9917",
```

2022-02-11 14:28 UTC, mishraprafful commented
@johnnyaug Thanks for your review, I've made the relevant changes. 🙂

2022-02-21 09:26 UTC, johnnyaug approved these changes

2022-02-21 09:26 UTC, merged