Minor bagel changes
treeverse/lakeFS pull request #2946
Opened 2022-02-14 12:26 UTC by Jonathan-Rosenberg

Commit messages describe the changes

2022-02-14 14:07 UTC, guy-har approved these changes
LGTM 
Thanks!

2022-02-14 14:07 UTC, guy-har commented on deployments/compose/docker-compose.yml
> +    name: bagel
add new line

2022-02-15 07:59 UTC, johnnyaug approved these changes

2022-02-15 12:41 UTC, nopcoder requested changes
minor changes

2022-02-15 12:41 UTC, nopcoder commented on deployments/compose/jupyter/Dockerfile
> +RUN apt update -y && apt install -y curl
can use wget without the package updates

2022-02-15 12:41 UTC, nopcoder commented on deployments/compose/jupyter/Dockerfile
> +ENV SPARK_HOME=/usr/local/spark-3.2.0-bin-hadoop3.2
already set in the base image

2022-02-15 12:41 UTC, nopcoder commented on deployments/compose/jupyter/Dockerfile
> +ENV HADOOP_VERSION=3.3.1
base image use the specific env var - choose another name

2022-02-16 06:20 UTC, arielshaqed approved these changes
Thanks! How was this tested? (Manually is perfectly fine)

2022-02-16 08:35 UTC, Jonathan-Rosenberg commented
> Thanks! How was this tested? (Manually is perfectly fine)

Manually.

2022-02-16 09:33 UTC, merged