[2550] Dont show GetStarted for empty commit
treeverse/lakeFS pull request #3041
Opened 2022-03-14 05:41 UTC by tshradheya

Fixes #2550

Only showing the GetStarted Page when the user is on main branch and branch is empty.

Selecting refs would show results even if empty

2022-03-15 14:21 UTC, tshradheya commented
@talSofer is there a way for me to update the label to pass all checks?

2022-03-17 11:00 UTC, nopcoder requested changes

2022-03-17 11:00 UTC, nopcoder commented on webui/src/lib/components/repository/tree.jsx
> +    if (results.length === 0 && path === "" && reference.type === "branch") {
We can use `RefTypeBranch` here.

2022-03-17 11:01 UTC, nopcoder commented
@tshradheya thanks for the contribution, I've updated the required label and added a small comment to your change.

2022-03-19 12:09 UTC, nopcoder approved these changes
LGTM!

2022-03-20 11:39 UTC, merged