API endpoint to get email configuration
treeverse/lakeFS pull request #3202
Opened 2022-04-11 20:05 UTC by shimi9276

Used for the frontend to check if an emailer exists and render email functionality based on that.

2022-04-11 20:19 UTC, nopcoder requested changes
- API should describe the configuration structure
- There is no need to check if something is configured by compare of one field. Unless we add enable/disable configuration, just return the configuration the behavior is they expect while looking at the configuration.
- read email configuration should be associated to policy, so you will need to update the information or add documentation on how to configure it.

2022-04-12 03:59 UTC, arielshaqed requested changes
There are potential security issues here,  too. Let's split this one up into 2 PRs: first a well-defined Swagger-only PR (with dummy code that sends an empty response in the implementation), then a follow-on to add the functionality.

2022-04-12 03:59 UTC, arielshaqed commented on api/swagger.yml
> +                type: object
Please specify an object type. Otherwise it will not be possible to use the API defined in this file to develop code.

2022-04-12 03:59 UTC, arielshaqed commented on pkg/api/controller.go
> +	writeResponse(w, http.StatusOK, c.Emailer.Params)
This exposes many params that must not be user visible. E.g. it may contain email server secrets.

2022-04-24 12:54 UTC, shimi9276 commented
Done is[ this pr](https://github.com/treeverse/lakeFS/pull/3220)

2022-04-24 12:54 UTC, closed without merging