Bump golangci-lint version and fix "a few" things
treeverse/lakeFS pull request #3391
Opened 2022-05-19 08:44 UTC by arielshaqed

Nothing major discovered, except for one bad use of append in a
test (fixed).

Also fixes #3390.

2022-05-19 09:03 UTC, nopcoder requested changes

2022-05-19 14:22 UTC, arielshaqed commented on cmd/lakectl/cmd/annotate.go
> +	return strings.SplitN(str, "\\n", 2)[0] // nolint: gomnd
Done!  (Also in 2 or 3000 other places, of course).

2022-05-19 14:24 UTC, arielshaqed commented on cmd/lakectl/cmd/dbt_util.go
> +	DBTCmd := exec.Command("dbt", "ls", "--resource-type", resourceType, "--select", strings.Join(selectValues, " "), "--output", "json", "--output-keys", resourceJSONKeys) // nolint: gosec
:+1:

2022-05-19 14:26 UTC, arielshaqed commented on cmd/lakectl/cmd/fs.go
> +//nolint:gochecknoinits, gomnd
Yup...

2022-05-23 13:53 UTC, nopcoder approved these changes

2022-05-31 13:02 UTC, merged