Docs: update commitment to OSS
treeverse/lakeFS pull request #3465
Opened 2022-06-07 10:25 UTC by ozkatz

2022-06-07 12:54 UTC, peacing commented on docs/commitment.md
> +As part of our commitment to the open source values of transparency and interoperability, we believe everyone should be able to enjoy these benefits, regarless of whether or not they choose to use th
small typo: regarless >> regardless

2022-06-07 13:06 UTC, johnnyaug requested changes

2022-06-07 13:06 UTC, johnnyaug commented on docs/commitment.md
> +In other words, we commit that the following capabilities are *and will remain* open source as part of lakeFS:
```suggestion
For that reason, we commit that the following capabilities are *and will remain* open source as part of lakeFS:
```

2022-06-07 13:06 UTC, johnnyaug commented on docs/commitment.md
> +lakeFS Cloud's vision is to provide a managed, usable data versioning and management solution for data practitioners, by leveraging the open source technology behind lakeFS and building added capabil
```suggestion
The vision of lakeFS Cloud is to provide a managed data versioning and management solution for data practitioners. lakeFS Cloud  will leverage the lakeFS open source technology and add capabilities and unique features on top of it.
```

2022-06-09 13:25 UTC, johnnyaug approved these changes

2022-06-10 10:45 UTC, nopcoder approved these changes

2022-06-10 11:38 UTC, merged