Garbage Collector: Eliminate double slash in URL in GC
treeverse/lakeFS pull request #3525
Opened 2022-06-19 13:32 UTC by Jonathan-Rosenberg

The garbage collector sometimes operates over path with double slashes in them. 
For example: `s3://some-bucket/some-path//_lakefs/logs/gc/summary`.
This PR aims to fix this problem.

### Problems:
1. The lakeFS server sends the suffix of the different paths with `/` as a delimiter as the first character to the `formatPathWithNamespace` function that expects it to not include the delimiter as a prefix.
2. The GC code attached a `/` prefix to the `_lakefs` path. That resulted in a double slash if the storage namespace ended with a slash.

### Mitigation: 
1. **lakeFS**: Pass the appropriate suffixes to the `formatPathWithNamespace` function.
2. **GarbageCollector**: Make sure that the storage namespace ends with a slash and build the location properly.

2022-06-20 06:17 UTC, arielshaqed requested changes
I'd like us to make the upgrade process explicit here.  This is the requested change.

Also what do we want to do about GCS and Azure?  We could check what happens and fix if needed before releasing GC for these two backends.

2022-06-20 07:00 UTC, talSofer reviewed
Thank you for working on this bug! this is a must-fix for Azure on GC so timing is great. 

How was this tested?

2022-06-20 08:01 UTC, Jonathan-Rosenberg commented on pkg/graveler/retention/garbage_collection_manager.go
> +	commitsFileSuffixTemplate   = "%s/retention/gc/commits/run_id=%s/commits.csv"
If I'm not mistaken, only S3 users can use the GC (as @talSofer and @lynnro314 figured out recently).
If this is the case, this isn't a breaking change as the Go AWS SDK client writes it to a single slash path.

2022-06-20 08:04 UTC, Jonathan-Rosenberg commented on clients/spark/core/src/main/scala/io/treeverse/clients/GarbageCollector.scala
> +    val strippedKey = key.stripPrefix("/")
The method is not aware of the calls, it sanitizes the input...

2022-06-21 05:50 UTC, talSofer commented on pkg/graveler/retention/garbage_collection_manager.go
> +	commitsFileSuffixTemplate   = "%s/retention/gc/commits/run_id=%s/commits.csv"
This part fixes another bug we found in the GC-Azure integration! double thanks @Jonathan-Rosenberg :) 
Up until this fix, while trying to get gc rules we got the following error:
```
: invalid namespace
500 Internal Server Error
```
But removing the superfluous "/" fixed it for the following reason - 
Before the fix, "/_lakefs/settings/retention/gc/rules/config.json" was parsed without returning an error to https://github.com/treeverse/lakeFS/blob/a21c0fcfb8d299ac5deb9e4e26bc66e8c8352f35/pkg/block/azure/adapter.go#L91, leading to an incorrect URL resolution trying to resolve it as a fully qualified URI (that includes a namespace). After the fix, "_lakefs/settings/retention/gc/rules/config.json" is resolved as a non-fully qualified URI.

2022-06-21 08:27 UTC, arielshaqed commented on pkg/graveler/retention/garbage_collection_manager.go
> +	commitsFileSuffixTemplate   = "%s/retention/gc/commits/run_id=%s/commits.csv"
As discussed F2F, let's solve this with a note on the CHANGELOG.  S3 users should continue to be unaffected by this.  Non-S3 users should not exist, as GC has never worked for them.  So you're right, and I agree a note is enough.

2022-06-21 08:32 UTC, merged