Docs proofreading - integrations category
treeverse/lakeFS pull request #3675
Opened 2022-07-18 10:10 UTC by arouyan

@johnnyaug I proofread all the pages in the category Integrations

2022-07-20 14:55 UTC, johnnyaug requested changes

2022-07-21 07:45 UTC, arouyan commented on docs/integrations/python.md
> +Install the Python Client using pip:
Double-checked, you're right - no need to capitalize

2022-07-21 11:32 UTC, arouyan commented on docs/integrations/boto.md
> +To use Boto with lakeFS alongside S3, check out the [Boto S3 Router](https://github.com/treeverse/boto-s3-router){:target="_blank"}. It will route
Got it, I thought it was a name of a feature or module - then an article makes sense sometimes. Will delete

2022-07-24 14:01 UTC, johnnyaug approved these changes

2022-07-24 14:02 UTC, merged