KV Store: Implement settings manager
treeverse/lakeFS pull request #3848
Opened 2022-08-04 19:31 UTC by N-o-Z

Implemented settings manager in DB only
Added blockstore access in migration flow and verified it works
Closes #3785 #3830

2022-08-07 07:11 UTC, itaiad200 approved these changes
Looks great! Approving but consider the following:
1. Introduced a flaky test, please use a dedicated one for the kv impl.
2. Add settings to the migration test in esti

2022-08-07 07:11 UTC, itaiad200 commented on pkg/graveler/settings/manager.go
> +		return fmt.Errorf("update settings: %w", graveler.ErrTooManyTries)
Do we log the errors that occur? If we maxed our retries with outputing any indication for the reason then it's hard for the user/developer to understand what went wrong..

2022-08-07 07:11 UTC, itaiad200 commented on pkg/graveler/settings/manager_test.go
>  		}()
This is flaky by nature in the KV implementation. There's a chance that a certain goroutine will fail to update the settings within the number of retries allocated to it.

2022-08-07 07:11 UTC, itaiad200 commented on pkg/graveler/settings/manager_test.go
> +// TODO: locking is irrelevant for KV, create a new test for it
Let's add this now instead of this flaky test

2022-08-07 09:07 UTC, itaiad200 approved these changes

2022-08-07 15:17 UTC, N-o-Z commented
@itaiad200 Please review again with changes to Mem Adapter and MigrateTest

2022-08-08 07:50 UTC, itaiad200 requested changes

2022-08-08 07:50 UTC, itaiad200 commented on pkg/block/mem/adapter.go
> +func FetchStore(params params.Mem) *Adapter {
Why would I call `FetchStore` with `params.ReuseStore=false`? I think it makes this parameter or this function redundant.

2022-08-08 07:50 UTC, itaiad200 commented on pkg/config/template.go
> +			ReuseStore bool `mapstructure:"reuse_store"`
It's an in-memory test only implementation, I don't understand why we would like to add this flag to the configuration of lakeFS

2022-08-08 07:50 UTC, itaiad200 commented on pkg/graveler/settings/manager.go
> +			logging.Default().WithError(err).Warn("Predicate failed on settings update. Retrying")
Warning is preferred and not an error, since this is expected for some usages of the settings manager.

2022-08-08 11:49 UTC, itaiad200 approved these changes
LGTM 💪 🍄 🎹 🎵

2022-08-08 11:53 UTC, merged