Fix dynamodb secure password and remove beta
treeverse/lakeFS pull request #3897
Opened 2022-08-14 13:41 UTC by nopcoder

2022-08-14 13:52 UTC, itaiad200 approved these changes

2022-08-14 13:56 UTC, N-o-Z requested changes
GetKVParams update is missing

2022-08-14 14:40 UTC, N-o-Z requested changes
Esti dynamoDB docker yaml :D

2022-08-15 09:01 UTC, N-o-Z approved these changes
👍🏽

2022-08-15 09:03 UTC, merged