Test: Create KV test driver with callback. Add test for nil interface
treeverse/lakeFS pull request #4112
Opened 2022-09-05 09:08 UTC by N-o-Z

2022-09-06 10:24 UTC, itaiad200 requested changes
I suggest giving mockgen a spin before creating our own mock-with-callbacks implementations.

2022-09-06 10:24 UTC, itaiad200 commented on pkg/kv/testdriver/store.go
> +package testdriver
I think you reimplemented the code of mockgen, it gives you exactly what you need here.

2022-09-06 10:24 UTC, itaiad200 requested changes
I suggest giving mockgen a spin before creating our own mock-with-callbacks implementations.

2022-09-07 09:53 UTC, eden-ohana commented on pkg/kv/kvtest/store.go
> +	return testdriver.NewTestStore(store)
why not test the actual store?

2022-09-07 12:43 UTC, eden-ohana commented on pkg/kv/iterators_test.go
> +	itr = kv.NewPartitionIterator(ctx, store, (&kvtest.TestModel{}).ProtoReflect().Type(), modelPartitionKey)
duplication?

2022-09-13 09:54 UTC, N-o-Z commented
- Resolved in #4118

2022-09-13 09:54 UTC, closed without merging