4227 update dev/test env usecase with demo notebooks and walkthrough video
treeverse/lakeFS pull request #4277
Opened 2022-09-29 04:29 UTC by vinodhini8694

Updated the docs and added demo notebook reference as well.
TODO: Walkthrough video to be embedded.

2022-10-02 07:20 UTC, adipolak approved these changes
looks great! Added one suggestion. Thanks for this PR!

2022-10-02 07:20 UTC, adipolak commented on docs/use_cases/iso_env.md
> +## How do I create dev/test environments with lakeFS?
"## How do I create an isolated data dev/test environment with lakeFS?

2022-10-02 07:20 UTC, adipolak commented on docs/use_cases/iso_env.md
> +git clone https://github.com/treeverse/lakeFS-samples.git && cd 03-apache-spark-python-demo
love the usage of the sample repository!!!

2022-10-09 09:28 UTC, johnnyaug requested changes

2022-10-09 09:28 UTC, johnnyaug commented on docs/use_cases/iso_env.md
> +lakeFS supports UI, CLI (`lakectl` commandline utility) and several client API [integrations](../integrations) to run the git-like operations. Let us explore how to create dev/test environments using
```suggestion
lakeFS supports UI, CLI (`lakectl` commandline utility) and several client API [integrations](../integrations) to run Git-like operations. Let us explore how to create dev/test environments using each of these options below.
```

2022-10-09 09:28 UTC, johnnyaug commented on docs/use_cases/iso_env.md
> +You can create a new branch say `test-env` by going to the branches tab and clicking `Create branch`. Once it is successful, we see two branches under the repo: `main` and `test-env`.
```suggestion
You can create a new branch (say, `test-env`) by going to the _Branches_ tab and clicking _Create Branch_. Once it is successful, you will see two branches under the repo: `main` and `test-env`.
```

2022-10-09 09:28 UTC, johnnyaug commented on docs/use_cases/iso_env.md
> +Now, you can add, modify or delete the data files in the `test-env` branch without affecting the data in the main branch.
```suggestion
Now you can add, modify or delete objects under the `test-env` branch without affecting the data in the main branch.
```

2022-10-09 09:28 UTC, johnnyaug commented on docs/use_cases/iso_env.md
> +Adding or deleting files from different branches in a lakeFS repo can be performed from the UI as shown above. However, to perform complex transformations on the data using Spark or other compute eng
```suggestion
Adding or deleting objects to different branches in a lakeFS repository can be performed from the UI as shown above. However, to perform complex transformations using Spark or other compute engines, you will need to use lakeFS clients.
```

2022-10-09 09:28 UTC, johnnyaug commented on docs/use_cases/iso_env.md
> +To upload a file to the `my-repo`, use the following command.
```suggestion
To upload an object to the `my-repo`, use the following command.
```

2022-10-09 09:28 UTC, johnnyaug commented on docs/use_cases/iso_env.md
> +        message='Added my first file!',
```suggestion
        message='Added my first object!',
```

2022-10-09 09:28 UTC, johnnyaug commented on docs/use_cases/iso_env.md
> +This use case shows how you can create dev/test data environments using lakeFS branches. The following tutorial will use an existing lakeFS environment (i.e., playground) and a jupyter notebook, pyth
Not clear.

2022-10-09 23:35 UTC, vinodhini8694 commented on docs/use_cases/iso_env.md
> +This use case shows how you can create dev/test data environments using lakeFS branches. The following tutorial will use an existing lakeFS environment (i.e., playground) and a jupyter notebook, pyth
Fixed it.

2022-10-09 23:38 UTC, vinodhini8694 commented
> I am not sure about repeating in our documentation the documentation of the samples-repo - but I am not the expert on this. I would ask for a second opinion though.


@iddoavn  We had a different example and code snippet in the docs and in the sample notebook. So I updated the docs to use the same snippet as lakeFS samples notebook.

2022-10-11 15:33 UTC, adipolak approved these changes

2022-10-11 15:43 UTC, vinodhini8694 commented
@johnnyaug @iddoavn Added the requested changes - except embedding the webinar video recording. Can we move forward?

2022-10-12 07:45 UTC, iddoavn commented
@vinodhini8694 - why not embed the video?

2022-10-12 07:47 UTC, iddoavn requested changes
I think we should embed the video as it shows the end-to-end process of what is described here. 
We should start it on the point of the demo using this link: https://youtu.be/VtGNw2YPFEU?t=533

2022-10-15 17:53 UTC, vinodhini8694 commented
@iddoavn Embedded the video to the page as well.

2022-10-15 17:53 UTC, merged