Add skip flag to skip Esti tests
treeverse/lakeFS pull request #4298
Opened 2022-10-02 15:29 UTC by idanovo

2022-10-03 13:18 UTC, nopcoder requested changes
Can we use the same syntax as '-run' - if go will add this capability they will keep the same syntax probably and it will be easy to migrate.

2022-10-03 13:19 UTC, nopcoder requested changes

2022-10-03 13:19 UTC, nopcoder commented on esti/main_test.go
> +		t.Skip(fmt.Printf("Skip on test: %s", t.Name()))
just `SkipNow()` as we don't give any good explanation :)

2022-10-03 14:46 UTC, nopcoder requested changes

2022-10-03 14:47 UTC, idanovo commented on esti/main_test.go
> +	testsToSkipRegex, _ = regexp.Compile(*testsToSkip)
In case we have an error I should fail the run or just run all the tests?

2022-10-03 16:22 UTC, nopcoder requested changes

2022-10-03 16:22 UTC, nopcoder commented on esti/main_test.go
> +		log.Fatal(err)
```suggestion
		log.Fatalf("Skip pattern '%s' failed to compile:", *testsToSkip, err)
```

2022-10-03 16:22 UTC, nopcoder commented on esti/main_test.go
> +	testsToSkipRegex, err = regexp.Compile(*testsToSkip)
if *testsToSkip != "" {
}

2022-10-03 16:22 UTC, nopcoder commented on esti/main_test.go
> +	if testsToSkipRegex.String() != "" && testsToSkipRegex.MatchString(t.Name()) {
testsToSkipRegex
```suggestion
	if testsToSkipRegex != nil && testsToSkipRegex.MatchString(t.Name()) {
```

2022-10-04 08:25 UTC, nopcoder approved these changes
LGTM! hope we will have it as part of the next Go release

2022-10-04 08:25 UTC, merged