Move audit logs tag to the right place
treeverse/lakeFS pull request #4402
Opened 2022-10-19 13:39 UTC by idanovo

2022-10-19 15:20 UTC, nopcoder requested changes

2022-10-19 15:20 UTC, nopcoder commented on pkg/httputil/logging.go
> +				logging.LogAudit: "API",
I don't think we need this one, at least not here - the same middleware is used for logging s3 and api requests.
The field "service_name" value can be "s3_gateway" or "rest_api" to capture which instance of this middleware we report from.
If service_name is used more than this middleware we can mark this log with a different label to separate it from other logging lines - but it is not just API.

2022-10-20 07:29 UTC, ortz commented
@idanovo I'm not sure I understand how this differentiates between the different API calls. 
Mind providing more context?

2022-10-20 13:18 UTC, idanovo commented
> @idanovo I'm not sure I understand how this differentiates between the different API calls. Mind providing more context?

The purpose of this PR is to have the audit logs tag only for the logs that audit the calls the user does (rest/S3 gateway). 
Currently, we use this tag also for irrelevant logs.

2022-10-20 13:43 UTC, merged