[API breaking change] add prefix change indicator
treeverse/lakeFS pull request #4403
Opened 2022-10-19 14:03 UTC by eden-ohana

closes #4068 
documentation will be added as part of #4070

2022-10-20 08:03 UTC, itaiad200 requested changes
Thanks! Some questions & comments:
1. Does the UI support it out of the box? I think we should at least introduce new colouring to changed prefixes to differentiate them from changed objects.
2. We need some testing (new or modify existing) that validates the new behaviour.
3. I think we should make the documentation changes in this PR, #4070 is a whole different issue (although it involves docs too..).

2022-10-23 14:39 UTC, johnnyaug commented on pkg/api/transform.go
> +		return "prefix changed"
```suggestion
		return "changes under prefix"
```

2022-10-24 13:15 UTC, johnnyaug commented
@itaiad200 - please, no more colors in the diff screen. The UI shows a folder icon, indicating that this is a prefix and not a single object. I would argue that this enough.

2022-10-24 13:37 UTC, eden-ohana commented
@itaiad200 
1. Currently, The UI shows the same color for prefix as for change. I don't think we should add another color for it, maybe add text with "changes under this prefix" but I'm not sure it's necessary because it has a change color and folder icon.
2. Done
3. There isn't an explanation on the docs about the current diff behavior, on #4070 I'm adding a diff section on the docs that we can explain there in detail. unless you have an idea where to document it for now.

2022-10-24 13:38 UTC, eden-ohana commented on pkg/api/transform.go
> +		return "prefix changed"
done

2022-10-25 08:30 UTC, itaiad200 commented
<img src="https://media4.giphy.com/media/l0MYxqKEmJoL150TC/giphy.gif"/>

2022-10-25 12:31 UTC, eden-ohana commented
![image](https://user-images.githubusercontent.com/71877898/197773450-af894ce1-abf0-41e3-8165-6c9756b6ab35.png)

2022-10-25 12:35 UTC, itaiad200 approved these changes
LGTM
Please change the hover message on the directory symbol

2022-10-25 20:45 UTC, merged