Docs: Fix Airbyte documentation supported version
treeverse/lakeFS pull request #4484
Opened 2022-10-26 19:11 UTC by N-o-Z

Closes #4398

2022-10-27 11:43 UTC, nopcoder requested changes

2022-10-27 11:43 UTC, nopcoder commented on docs/integrations/airbyte.md
> +You can take advantage of lakeFS consistency guarantees and [CI/CD capabilities](../data_lifecycle_management) when ingesting data to S3 using lakeFS:
Update the title of the link 'CI/CD...' to match the page, "Data Lifecycle Management"

2022-10-27 11:43 UTC, nopcoder commented on docs/integrations/airbyte.md
> +If using Airbyte OSS, please ensure you are using S3 destination connector version 0.3.17 or higher.
Link to the one we like the user to use (https://airbyte.com/connectors/s3)

2022-10-29 00:37 UTC, vinodhini8694 approved these changes
LGTM

2022-10-30 20:37 UTC, nopcoder approved these changes
lgtm!

2022-10-30 21:30 UTC, merged