Add video to run lakeFs locally
treeverse/lakeFS pull request #4539
Opened 2022-11-01 15:19 UTC by iddoavn

FIX #4538 

Added a video to running locally + changes addressing it as local run vs local install.

2022-11-03 14:47 UTC, adipolak requested changes

2022-11-03 14:47 UTC, adipolak commented on docs/quickstart/installing.md
> +# Run lakeFS Locally
It's better to use Install lakeFS locally instead of run, as from a developer point of view, the user essentially install it.

2022-11-04 16:12 UTC, kesarwam approved these changes

2022-11-07 14:22 UTC, adipolak approved these changes
LGTM

2022-11-07 14:43 UTC, closed without merging