Docs: restructure tree and unify pages
treeverse/lakeFS pull request #4572
Opened 2022-11-08 13:04 UTC by ozkatz

Trying to simplify the flow of getting a working lakeFS installation (non-local)
Additionally, removed the standalone "spark" page which didn't provide any useful information on its own.

This is part of wider reorganization of the documentation structure.

2022-11-09 08:02 UTC, johnnyaug requested changes
Thanks! 
We are now missing the part of creating the first user and the first repository.

2022-11-10 09:36 UTC, ozkatz commented on docs/deploy/onprem.md
> +nav_order: 40
Done

2022-11-10 09:36 UTC, ozkatz commented on docs/deploy/onprem.md
> +   ⚠️ Notice that the lakeFS Blockstore type is set to `s3` - This configuration works with S3-compatible storage engines such as [MinIO](https://min.io/){: target="blank" }.
True! Added as prerequisite

2022-11-10 09:37 UTC, ozkatz commented on docs/deploy/gcp.md
> +next:  ["Import data into your installation", "../howto/import.html"]
Agree! Added to all deployment guides these missing steps.

2022-11-10 09:37 UTC, ozkatz commented on docs/howto/index.md
> +nav_order: 60
Hopefully will very soon resolve itself with the new hierarchy and order :)

2022-11-10 11:47 UTC, ozkatz commented on docs/howto/index.md
> +nav_order: 60
Done!

2022-11-10 15:06 UTC, johnnyaug reviewed
Looks really, really good. 
There are still some comments - not all of them need to be handled in this PR, but I think some do.

2022-11-24 13:15 UTC, ozkatz commented
@johnnyaug Would appreciate the help! I accept all comments you've made but haven't had the time to implement them. If you can pick up the rest I'll be happy to approve and we can merge today!

2022-11-28 08:23 UTC, johnnyaug commented
@ozkatz on it

2022-11-28 11:34 UTC, johnnyaug approved these changes

2022-11-28 11:49 UTC, merged