remove ui from go tests
treeverse/lakeFS pull request #4631
Opened 2022-11-22 11:33 UTC by johnnyaug

2022-11-22 12:18 UTC, nopcoder requested changes

2022-11-22 12:18 UTC, nopcoder commented on Makefile
> +	touch ./webui/dist/index.html
Not sure we would like it in the Makefile - or alternative enable specific step that will just generate the Go files that will skip the node/webui stuff.

2022-11-22 12:18 UTC, nopcoder commented on clients/spark/build.sbt
> +// lazy val examples312 = generateExamplesProject(spark312Type).dependsOn(core312)
Part of the PR?

2022-11-22 12:19 UTC, johnnyaug commented on clients/spark/build.sbt
> +// lazy val examples312 = generateExamplesProject(spark312Type).dependsOn(core312)
oops!

2022-11-24 10:53 UTC, nopcoder approved these changes
LGTM

2022-11-24 11:15 UTC, merged