GC+: Ignore external addresses in CommittedAddressLister
treeverse/lakeFS pull request #4715
Opened 2022-11-30 15:24 UTC by N-o-Z

Closes #4641

2022-12-01 12:55 UTC, johnnyaug approved these changes
Awesome!

2022-12-04 09:28 UTC, itaiad200 requested changes

2022-12-04 09:28 UTC, itaiad200 commented on clients/spark/core/src/main/scala/io/treeverse/gc/CommittedAddressLister.scala
> +            col("address_type").contains("://"))
```suggestion
            !col("address_type").contains("://"))
```

2022-12-04 09:28 UTC, itaiad200 commented on clients/spark/core/src/main/scala/io/treeverse/gc/CommittedAddressLister.scala
> +            col("address_type").contains("://"))
Need to check that if you split by `://` you get at least 2 parts, and that the first one doesn't contain `/` or `:`.

2022-12-04 10:27 UTC, itaiad200 approved these changes

2022-12-04 11:35 UTC, merged