GC+: Add exceptions and error handling
treeverse/lakeFS pull request #4806
Opened 2022-12-13 14:44 UTC by N-o-Z

Closes #4803

2022-12-15 13:38 UTC, nopcoder requested changes
Looks good - minor comments, my main concern before we make this one is the `lakefs.gc.do_mark=true` as it will change the behaviour we just documented does not align with the current GC process.

2022-12-15 13:38 UTC, nopcoder commented on clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala
> +      throw new ParameterValidationException("Can't provide mark ID for mark mode. Exiting...")
can remove the elses

2022-12-15 13:38 UTC, nopcoder commented on clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala
> +  private def runPath(storageNamespace: String, runID: String): String = {
Can we name it 'formatRunPath' or something that we don't think we are actually running something.

2022-12-15 13:38 UTC, nopcoder commented on clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala
> -        success = false
Nice - just initialize `success` with false and set it to true at the end of the 'try' scope.

2022-12-25 10:43 UTC, N-o-Z commented
> Looks good - minor comments, my main concern before we make this one is the `lakefs.gc.do_mark=true` as it will change the behaviour we just documented does not align with the current GC process.

Aligned defaults with committed garbage collector for now.
Modified the documentation (which had a bug in it as well)

2022-12-25 15:02 UTC, nopcoder approved these changes
LGTM - thanks!

2022-12-25 15:33 UTC, merged