added bounty hunter program doc
treeverse/lakeFS pull request #4847
Opened 2022-12-21 20:30 UTC by hiccups28

still need to do the formatting

2022-12-21 20:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=4847) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=4847) before we can accept your contribution.<br/><hr/>**Ankit Srinivas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=4847) it.</sub>

2022-12-22 10:25 UTC, adipolak requested changes

2022-12-22 10:25 UTC, adipolak commented on docs/lakeFSBountyHunterProgram.md
> +lakeFS Bounty Hunter Program
this is missing a header that connects all our new pages together. 
@hiccups28 take a look at this one as an example - https://raw.githubusercontent.com/treeverse/lakeFS/master/docs/contributing.md

2022-12-24 22:32 UTC, nopcoder commented on docs/lakeFSBountyHunterProgram.md
> +lakeFS Bounty Hunter Program
These programs called "Bug Bounty" without the hunter

2022-12-25 09:41 UTC, johnnyaug requested changes
Please rename the file to conform with the convention of lower_snake_case.

Is this going to be a page in the docs, or is this an internal document?

If it's going to be public, it still requires proofreading - there are a lot of typos. Also, missing metadata headers (see at the top of other doc page). Of course, also missing the videos, links and usage of markdown formatting.

2022-12-25 09:41 UTC, johnnyaug commented on docs/lakeFSBountyHunterProgram.md
> +lakeFS Bounty Hunter Program is a community program to encourage lakeFS Active OSS users to engage with the source code and improve lakeFS capabilities. The program is designed to reward community me
No need to capitalize "Active" throughout this doc.

2022-12-25 09:41 UTC, johnnyaug commented on docs/lakeFSBountyHunterProgram.md
> +Getting Started
Please use markdown headings.

2022-12-25 09:41 UTC, johnnyaug commented on docs/lakeFSBountyHunterProgram.md
> +Before we get started, please see the requirements to join the program:
```suggestion
### Requirements
```

2022-12-25 09:41 UTC, johnnyaug commented on docs/lakeFSBountyHunterProgram.md
> +To be an active OSS users, must be apart of 6 versions,
What?

2022-12-25 09:41 UTC, johnnyaug commented on docs/lakeFSBountyHunterProgram.md
> +Must be a member of lakeFS Community Slack
```suggestion
- To join the program, the user must have a lakeFS installation that has been active for at least 1 month.
- The user must be a member of the lakeFS community Slack.
```

2022-12-25 09:41 UTC, johnnyaug commented on docs/lakeFSBountyHunterProgram.md
> +New Users will receive an email to verify that they have been accepted to the Bounty Hunter Program and will be given a link to access the bounties.
```suggestion
New Users will receive an email to confirm that they have been accepted to the Bounty Hunter Program and will be given a link to access the bounties.
```

2022-12-25 09:41 UTC, johnnyaug commented on docs/lakeFSBountyHunterProgram.md
> +All new issues submitted to the lakeFS bounty program will be reviewed by a lakeFS Developer. Here are the list of submission acceptable for review:
```suggestion
All new issues submitted to the lakeFS bounty program will be reviewed by a lakeFS developer. Here is the list of submission types acceptable for review:
```

2023-01-04 20:10 UTC, vinodhini-sd commented
@adipolak Closing the PR as we decided to move forward with a web landing page instead of docs.

2023-01-04 20:10 UTC, closed without merging