UGC safeness integration tests
treeverse/lakeFS pull request #5059
Opened 2023-01-17 22:27 UTC by eden-ohana

closes #4830 

haven't added the copy object test yet - waiting for the PR

2023-01-18 08:19 UTC, itaiad200 reviewed
I only noticed it's a draft PR half way through. Still posting 2 comments as I believe they might help.

2023-01-18 08:19 UTC, itaiad200 commented on clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala
> +        listTime = startListTime
```suggestion
        val (dataDF, listTime) = listObjects(storageNamespace, cutoffTime)
```

2023-01-18 08:19 UTC, itaiad200 commented on clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala
> +      "start_list_time" -> DateTimeFormatter.ISO_INSTANT.format(startTime),
Probably a dumb question, but why do we need both? What does `start_list_time` give us that `start_time` don't?

2023-01-18 17:14 UTC, itaiad200 requested changes
I enjoyed reading this, very well structured code. 
Requesting changes mostly for the first bullet of the missing test coverage.

2023-01-18 17:14 UTC, itaiad200 commented on esti/ugc_test.go
> +		if obj.LastModified.Before(startListTime) {
OK now I see what this test is all about. You upload many objects and delete them all. Some are written before the cutoff and some after the cutoff. Here you validate that all objects before the cutoff are deleted which is great.
I think the previous test checks that too and also that committed/uncommitted objects remain (i.e. not deleted).
Here's what I think is still missing:
1. Validation that deleted objects that were created after the cutoff are not deleted.
2. Validation that copied objects are not deleted (i.e. copy table works). It's a difficult one, you need to copy while deleting the source object, at the exact time that the uncommitted objects are being listed for UGC, yeah..

2023-01-19 08:49 UTC, eden-ohana commented on clients/spark/core/src/main/scala/io/treeverse/gc/UncommittedGarbageCollector.scala
> +      "start_list_time" -> DateTimeFormatter.ISO_INSTANT.format(cutoffTime),
done

2023-01-19 08:51 UTC, eden-ohana commented on esti/ugc_test.go
> +func listRepositoryUnderlyingStorage(t *testing.T, ctx context.Context, repo string) ([]Object, block.QualifiedPrefix) {
done

2023-01-19 08:52 UTC, eden-ohana commented on esti/ugc_test.go
> +	s3Client := newDefaultS3Client()
done

2023-01-19 08:52 UTC, eden-ohana commented on esti/ugc_test.go
> +	listInput := &s3.ListObjectsInput{
done

2023-01-19 08:52 UTC, eden-ohana commented on esti/ugc_test.go
> +	startListTime, err := getReportCutoffTime(s3Client, qp.StorageNamespace, reportPath)
done

2023-01-19 08:53 UTC, eden-ohana commented on esti/ugc_test.go
> +				uploadAndDeleteSafeTestData(t, ctx, repo)
for the ugc to delete it

2023-01-19 08:58 UTC, eden-ohana commented on esti/ugc_test.go
> +	_, err = client.LinkPhysicalAddressWithResponse(ctx, "repo1", "main", &api.LinkPhysicalAddressParams{
done

2023-01-19 09:16 UTC, eden-ohana commented on esti/ugc_test.go
> +		Checksum:  "afb0689fe58b82c5f762991453edbbec",
example from the tests

2023-01-23 16:17 UTC, itaiad200 approved these changes

2023-01-23 19:05 UTC, eden-ohana commented on esti/ugc_test.go
done

2023-01-23 19:27 UTC, merged