Fix: Ingest walk function and tests
treeverse/lakeFS pull request #5095
Opened 2023-01-25 12:11 UTC by N-o-Z

Closes #5094

2023-01-25 15:44 UTC, N-o-Z commented
Test will pass after #5096 is merged

2023-01-26 10:49 UTC, nopcoder requested changes

2023-01-26 10:49 UTC, nopcoder commented on esti/ugc_test.go
> +		})
Just to be on the safe side
```suggestion
			LastModified: aws.TimeValue(obj.LastModified),
		})		
```

2023-01-26 10:51 UTC, nopcoder commented on esti/ugc_test.go
> +		})
without the space padding

2023-01-26 12:09 UTC, nopcoder approved these changes
LGTM!

2023-01-27 17:20 UTC, merged