Audit log docs
treeverse/lakeFS pull request #5157
Opened 2023-01-31 18:00 UTC by guy-har

2023-02-01 13:00 UTC, nopcoder requested changes

2023-02-02 06:19 UTC, guy-har commented on docs/audit.md
> +- Resource - `=`,`!=`, compare by string or regex
@nopcoder, so what would you suggest? 
I think it's important to state two things here 
1. it's `=` and not `==` or something else 
2. regex is supported

2023-02-02 12:07 UTC, nopcoder requested changes

2023-02-02 12:07 UTC, nopcoder commented on docs/audit.md
> +- Resource - `=`,`!=`, compare by string or regex
1. Agree
2. How do I specify if it is a string or regex - if there is no way - it means that it is always regex

2023-02-02 12:21 UTC, nopcoder approved these changes
Just specify the syntax all the rest looks good.

2023-02-02 16:00 UTC, rmoff reviewed
I've made some changes, including adding a bit of preamble to the top of the doc. 

The one changes I would suggest would be under `Filtering` to add an example or two.

2023-02-02 18:05 UTC, merged