KV health check for DynamoDB
treeverse/lakeFS pull request #5282
Opened 2023-02-19 14:30 UTC by idanovo

### Linked Issue

Closes #(Insert issue number closed by this PR)

---

## Change Description

### Background

Share context and relevant information for the PR: offline discussions, considerations, design decisions etc.

### Bug Fix

1. Problem - The reason for opening the bug
2. Root cause - Discovered root cause after investigation
3. solution - How was the bug fixed
      
### New Feature

Description of new feature

### Testing Details

How were the changes tested?
Added new unit tests / integration tests

### Breaking Change?

Does this change break any existing functionality? (API, CLI, Clients)

---

## Additional info

Logs, outputs, screenshots of changes if applicable (CLI / GUI changes)

---

### Contact Details

How can we get in touch with you if we need more info? (ex. email@example.com)

2023-02-21 09:17 UTC, idanovo commented on docs/reference/configuration.md
> +    + `database.dynamodb.aws_secret_access_key` `(string : )` - AWS secret access key.
```suggestion
    + `database.dynamodb.aws_secret_access_key` `(string : )` - AWS secret access key
```

2023-02-21 21:34 UTC, nopcoder requested changes

2023-02-21 21:34 UTC, nopcoder commented on pkg/config/config.go
> +			// Interval to run health check for the DynamoDB instance
Code doc should start with the name of the func/variable - `HealthCheckInterval` in this case.
No need to specify the default - it is done in the code later in this file.

2023-02-21 21:34 UTC, nopcoder commented on pkg/config/defaults.go
> +	viper.SetDefault("database.dynamodb.health_check_interval", 0*time.Minute)
no need - as far as I know the default for Duration type is zero.

2023-02-21 21:34 UTC, nopcoder commented on pkg/kv/dynamodb/store.go
> +		params: params}
```suggestion
		params: params,
	}
```

2023-02-21 21:34 UTC, nopcoder commented on pkg/kv/dynamodb/store.go
> +	const operation = "isTableExist"
The operation is `DescribeTable`

2023-02-21 21:34 UTC, nopcoder commented on pkg/kv/dynamodb/store.go
>  		}
Verify that for common setup - non-exists table is not consider as an error we like to report as an error.

2023-02-21 21:34 UTC, nopcoder commented on pkg/kv/params/database.go
> +	// Default: 0
1. code doc format
2. think it is maybe too much documentation - keep it here or on the configuration (here is fine)
3. remove the default - it is based on the configuration.

2023-02-21 21:34 UTC, nopcoder commented on pkg/kv/dynamodb/store.go
> +		s.ticker.Stop()
1. Logging - we should create logger in the driver level which holds the name of the store type - check local adapter. When possible we should pass logger or create one relevant to the service that log information.
2. Need wait group to wait under the check goroutine is done. This is just to be nice with the caller.
3. If we signal the goroutine to stop using a channel - just close the channel and move the ticker into `StartPeriodicCheck` (not a member) + defer close, so when we close the channel in `StopPeriodcCheck` the ticker will be stopped.

2023-02-22 08:58 UTC, itaiad200 commented on pkg/kv/dynamodb/store.go
> +	s.wg.Wait()
Will never return if `interval <= 0 `

2023-02-22 08:58 UTC, itaiad200 commented on pkg/kv/dynamodb/store.go
> +	s.wg.Wait()
or panic..

2023-02-22 15:36 UTC, nopcoder requested changes

2023-02-22 15:36 UTC, nopcoder commented on pkg/kv/dynamodb/store.go
> +		defer ticker.Stop()
1. Use single defer func() { ... }()
2. Don't make and use the channel from places, you may write to a nil channel. It is safe to always create a channel and call close(ch) on close. (like the fact that we use the waitgroup even when we do not start a goroutine)

2023-02-22 15:36 UTC, nopcoder commented on pkg/kv/dynamodb/store.go
> +	}
To simplify - just close the channel and wait for the wg.
Log probably in debug level - not so interesting.

2023-02-22 15:37 UTC, nopcoder commented on pkg/kv/params/database.go
> +	HealthCheckInterval time.Duration
remove whitespace

2023-02-23 07:02 UTC, nopcoder approved these changes
LGTM - just remove the extra `if` statement that is no longer required.

2023-02-23 07:02 UTC, nopcoder commented on pkg/kv/dynamodb/store.go
> +	if s.cancel != nil {
remove the if

2023-02-23 09:02 UTC, merged