Add an ASCIIlotl to the boot screen
treeverse/lakeFS pull request #5291
Opened 2023-02-20 16:44 UTC by rmoff

<img width="766" alt="image" src="https://user-images.githubusercontent.com/3671582/220162121-03b33ffa-5867-421a-a077-e0fe457fd9f4.png">

2023-02-20 17:29 UTC, nopcoder requested changes

2023-02-20 17:29 UTC, nopcoder commented on cmd/lakefs/cmd/run.go
> +│ If you're running lakeFS locally for the first time,
can you trim the leading spaces/tab at the end of this line

2023-02-20 17:29 UTC, nopcoder commented on cmd/lakefs/cmd/run.go
> +│ For support or any other question,                            >(.＿.)<
same here - from the diff it looks like there is a tab at the end

2023-02-20 17:37 UTC, nopcoder approved these changes
Great 😃

2023-02-20 20:00 UTC, ozkatz commented
I love everything about this PR.

2023-02-21 09:06 UTC, merged

2023-02-21 09:37 UTC, arielshaqed commented
Great PR but mislabelled.  This needs to be `include-changelog` (and possibly headline the release).