Make storage namespace reuse message clearer
treeverse/lakeFS pull request #5460
Opened 2023-03-13 09:16 UTC by rmoff

### Linked Issue

Closes #5363

---

## Change Description

### Background

One of the common actions a user test-driving lakeFS might do is creating and recreating repositories. 

This PR adds detail to the message that the user gets if they try to recreate a repo with the same name as 
one already used. 
      
### Testing Details

Local build and walk through to validate the error and repository creation. 

https://user-images.githubusercontent.com/3671582/224657529-c095187c-9b85-4d9b-9dac-30dc9c14d0da.mp4

2023-03-13 14:12 UTC, arielshaqed approved these changes
Thanks!

2023-03-16 15:48 UTC, nopcoder commented
@rmoff @arielshaqed Not sure we need to modify the error's text - Looks like inside the controller code at the point we return the error to the UI we control the text and override in some cases. This error value is used there is match the failure reason, there you can control the `reason` which we return to the user - which can be any text you like.

2023-03-16 15:52 UTC, nopcoder requested changes

2023-03-16 15:52 UTC, nopcoder commented on pkg/api/controller.go
> +var errStorageNamespaceInUse = errors.New("lakeFS repositories can't share storage namespace. This includes re-using storage namespaces from repositories since deleted")
Not sure we need to modify the error's text - we can keep it "storage namespace in use".
In the controller code I see that we already render a different text for the user - there you can format descriptive message.

2023-09-20 22:00 UTC, nopcoder commented
The fix by @johnnyaug https://github.com/treeverse/lakeFS/pull/5709 resolve this issue.

2023-09-20 22:00 UTC, closed without merging