Delta Lake Diff: Change default plugin loading
treeverse/lakeFS pull request #5495
Opened 2023-03-15 17:19 UTC by Jonathan-Rosenberg

## Change Description

First, look up the default directory for an executable named `delta` and register it if it's there.
Then test the different diff plugin configurations available and run over the previous registration if needed.

Why not the other way around?
Because it's easier and doesn't cost too much...

2023-03-16 11:14 UTC, arielshaqed approved these changes
# Nice!

2023-03-16 16:26 UTC, nopcoder requested changes

2023-03-16 16:26 UTC, nopcoder commented on pkg/plugins/diff/service.go
>  			if props.Version != nil {
I think we can remove the Version pointer from the configuration as we fallback to version 1 in the code - we can document that 0 is the default.

2023-03-16 16:26 UTC, nopcoder commented on pkg/plugins/diff/service.go
> +	if err != nil {
```suggestion
	_, err := os.Stat(deltaPath)
	if err != nil {
```

2023-03-19 10:20 UTC, Jonathan-Rosenberg commented on pkg/config/config.go
> +	Diff    map[string]DiffProps `mapstructure:"diff"`
Created an [issue](https://github.com/treeverse/lakeFS/issues/5518) for that and will be handled in the following iteration.

2023-03-22 09:27 UTC, merged