Delta Lake Diff: Enable feature
treeverse/lakeFS pull request #5508
Opened 2023-03-16 15:47 UTC by Jonathan-Rosenberg

### Linked Issue

Closes #[5191](https://github.com/treeverse/lakeFS/issues/5191)

---

## Change Description

* Enable the Delta Lake diff functionality
* Remove `Experimental Delta Diff` button

## Bug fix

Before this PR, while hovering over the `show table changes` button on a compare row, the row was shrinking because the CSS behavior was removing the padding from the button. This PR fixes it.

2023-03-16 16:51 UTC, nopcoder commented on webui/src/lib/components/repository/changes.jsx
> +    const disableDeltaDiff = JSON.parse(localStorage.getItem(`disable_delta_diff`));
1. Use single or double quotes
2. JSON.parse looks like overkill
```suggestion
    const disableDeltaDiff = localStorage.getItem('disable_delta_diff') === '1';
```

2023-03-16 17:00 UTC, eladlachmi requested changes
Looks good—a couple of minor comments. Also, please take a look at the lint errors.

2023-03-16 17:20 UTC, nopcoder commented on webui/src/styles/globals.css
> +.table .tree-entry-row .change-entry-row-actions .btn-link .btn.btn-link:hover {
`.btn-link:hover` ?

2023-03-19 11:09 UTC, Jonathan-Rosenberg commented on webui/src/lib/components/repository/changes.jsx
> +    const disableDeltaDiff = JSON.parse(localStorage.getItem(`disable_delta_diff`));
Thanks.
I'll remove that entirely.

2023-03-19 13:08 UTC, eladlachmi approved these changes
Thanks for implementing the fixes.
LGTM

2023-03-19 14:56 UTC, nopcoder commented on webui/src/util/tablesUtil.jsx
> +
can remove the empty like before the end of the function

2023-03-19 14:57 UTC, nopcoder approved these changes
LGTM!

2023-03-22 07:39 UTC, merged