Fix credentials list GUI sort
treeverse/lakeFS pull request #5892
Opened 2023-05-17 03:54 UTC by rishiravikumar-tul-scm

### Linked Issue

Closes #3691

---

## Change Description

### Background

On the Administration tab, the credentials are auto sorted by their ID. This change sorts the credentials by date, with the newest credentials on top

---

## Additional info
Administration Tab GUI with credentials sorted by creation date
![image](https://github.com/treeverse/lakeFS/assets/77828327/80dea54f-9cd5-4958-9bfc-2d1c913f282d)

---

### Contact Details

rishiravi.k98@gmail.com

2023-05-21 07:35 UTC, nopcoder requested changes
Paginated API - return sorted page will bring unexpected results.
If it is just user credentials to be sorted by data, you should consider sorting in the UI after pulling all the data.

2023-05-23 16:10 UTC, eladlachmi requested changes
This wasn't the intention of moving the sorting logic to the client since the client side also fetches only one data page at a time. For sorting to make sense, you must have all the results, not just a single page.

To do that, you must fetch all the pages, sort the results, and then implement the paging client side.

Imagine that you have two pages of data...
Page 1:
| Creation Date | Access Key ID |
|---------------|---------------|
| 23 May 2023  | AaBbC12345  |
| 20 May 2023  | BbCAa12345  |
| 10 May 2023  | CcBbA12345  |

Page 2:
| Creation Date | Access Key ID |
|---------------|---------------|
| 23 May 2023  | AaBbC12345  |
| 19 May 2023  | BbCAa12345  |
| 12 May 2023  | CcBbA12345  |

If you sort by creation date page-by-page, you won't get a reliably sorted list.

2023-05-25 08:08 UTC, nopcoder requested changes
The current UI code pull pages - sorting each page will not hold as the order of items are controlled by the server.
In order to have the sorted items on the client side means we need to pull all the list before we sort the data.

2023-06-22 10:28 UTC, itaiad200 commented
@rishiravikumar-tul-scm any update?

2023-06-22 10:52 UTC, rishiravikumar-tul-scm commented
Due to some personal bandwidth issues, I wasn't able to give time to this. Closing this for now

2023-06-22 10:52 UTC, closed without merging