Pyramid (TierFS): Random temporary file name
treeverse/lakeFS pull request #5918
Opened 2023-05-19 16:01 UTC by Jonathan-Rosenberg

2023-05-19 16:41 UTC, nopcoder requested changes

2023-05-21 09:05 UTC, Jonathan-Rosenberg commented on pkg/pyramid/tier_fs.go
> +		tmpFullPath := path.Join(tfs.fsLocalBaseDir, rPath)
done

2023-05-21 09:06 UTC, nopcoder approved these changes

2023-05-21 09:27 UTC, nopcoder requested changes

2023-05-21 09:27 UTC, nopcoder commented on pkg/pyramid/tier_fs.go
> +			_ = os.Remove(writer.Name())
Move the cleanup to the place io.Copy failed.

2023-05-21 09:43 UTC, nopcoder approved these changes

2023-05-21 11:34 UTC, nopcoder requested changes

2023-05-21 11:34 UTC, nopcoder commented on pkg/pyramid/directory.go
> +func (d *directory) createFile(path string, isTemp bool) (*os.File, error) {
Suggest to make this one createTempFile and drop the case where isTemp:false

2023-05-21 12:43 UTC, nopcoder approved these changes

2023-05-21 12:51 UTC, merged