Add documentation for disabling presigned url
treeverse/lakeFS pull request #6012
Opened 2023-06-02 10:15 UTC by guy-har

2023-06-02 10:33 UTC, ozkatz approved these changes
THANK YOU

2023-06-02 10:36 UTC, nopcoder requested changes

2023-06-02 10:36 UTC, nopcoder commented on docs/reference/configuration.md
> +* `blockstore.gs.disable_pre_signed_ui` `(bool : false)` - Disable use of pre-signed URL in the UI.
Relevant to all block store that holds this configuration - `diable_pre_signed` needs to `true` to enable this one.

2023-06-02 10:36 UTC, nopcoder commented on docs/reference/configuration.md
> +* `blockstore.gs.disable_pre_signed` `(bool : false)` - Disable use of pre-signed URL.
It is enabled by default on gs

2023-06-02 10:36 UTC, nopcoder commented on docs/reference/configuration.md
> +* `blockstore.s3.disable_pre_signed` `(bool : false)` - Disable use of pre-signed URL.
True by default

2023-06-02 10:36 UTC, nopcoder commented on docs/reference/configuration.md
> +* `blockstore.azure.disable_pre_signed` `(bool : false)` - Disable use of pre-signed URL.
True by default

2023-06-04 09:02 UTC, nopcoder approved these changes
LGTM!

2023-06-04 09:02 UTC, nopcoder approved these changes
LGTM!

2023-06-04 09:20 UTC, merged