Local Storage Range Allow 0:0
treeverse/lakeFS pull request #6116
Opened 2023-06-18 14:42 UTC by Isan-Rivkin

### Linked Issue

Fixes #6115

2023-06-18 15:31 UTC, N-o-Z commented on pkg/block/local/adapter.go
> +	if start < 0 || end < 0 {
```suggestion
	if start < 0 || end < start {
```

2023-06-18 15:31 UTC, N-o-Z requested changes
Change suggestion

2023-06-18 15:31 UTC, N-o-Z commented on pkg/block/local/adapter.go
> +	if start < 0 || end < 0 {
Consider this change

2023-06-18 15:45 UTC, Isan-Rivkin commented on pkg/block/local/adapter.go
> +	if start < 0 || end < 0 {
like +1

2023-06-18 17:19 UTC, N-o-Z approved these changes
Thanks !

2023-06-19 07:49 UTC, nopcoder approved these changes

2023-06-19 07:51 UTC, merged