Added basic documentation for iceberg support
treeverse/lakeFS pull request #6128
Opened 2023-06-21 10:52 UTC by lynnro314

close #6127

2023-06-22 13:35 UTC, rmoff approved these changes
I've gone through and updated this doc based on my understanding - however I think it would benefit from a second pair of reviewing eyes, and since I was chatting to @arielshaqed about references in table names etc he gets tagged here ;)

2023-06-25 13:33 UTC, arielshaqed requested changes
Neat, thanks!

**MUST** decide on which version people should run... and I'll approve!

2023-06-25 13:33 UTC, arielshaqed commented on docs/integrations/iceberg.md
> +lakeFS provides its own implementation of the `SparkCatalog`, which handles the writing of the Iceberg data to lakeFS as well as reading from it and branching. Using straightforward table identifiers
```suggestion
lakeFS provides its own implementation of `SparkCatalog`, which handles the writing of the Iceberg data to lakeFS as well as reading from it and branching. Using straightforward table identifiers you can switch between branches when reading and writing data: 
```

2023-06-25 13:33 UTC, arielshaqed commented on docs/integrations/iceberg.md
> +.config("spark.jars.packages", "org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.3.0,io.lakefs:lakefs-iceberg:0.0.1")
This version seems inconsistent with the POM version provided above.

2023-06-26 05:47 UTC, arielshaqed approved these changes
Yay, thanks!

2023-06-26 10:15 UTC, merged