Monitor (& log) KV retries during Graveler operations
treeverse/lakeFS pull request #6137
Opened 2023-06-22 21:10 UTC by arielshaqed

This will show up when branch operations or other updates collide.

Fixes #4563.

2023-06-22 21:12 UTC, arielshaqed commented
I will pull with either reviewer's approval.  Invited @Isan-Rivkin so he can
see deep lakeFS fun.

2023-06-26 07:19 UTC, itaiad200 requested changes
Thanks! Everything is easily fixable, let me know if you have any questions

2023-06-26 07:19 UTC, itaiad200 commented on pkg/graveler/graveler.go
> +	[]string{"operation", "repository"},
We shouldn't collect repos as metrics for 2 reasons:
1. Possible high cardinality
2. Possible user sensitive info. Again, not very likely but still.

It's not that any of the above is a high risk, but the gain of collecting the repos isn't big either. We don't collect repos anywhere else too.

2023-06-26 07:19 UTC, itaiad200 commented on pkg/graveler/graveler.go
> +	}
Can we have just one place where we log retries? You have Info + Trace here and Debug below. I think `Info` is too verbose for a somewhat expected retry, but anyway let's have it there or here and not both.

2023-06-26 07:19 UTC, itaiad200 commented on pkg/graveler/graveler.go
> +	g.monitorRetries(ctx, retries, repository.RepositoryID, branchID, "delete")
I do feel like this pattern should become the function itself or at least we should wrap this common functionality with another func:
```suggestion
	err := g.safeBranchWriteWithMonitor(ctx, log, repository, branchID,
		safeBranchWriteOptions{}, func(branch *Branch) error {
			return g.deleteUnsafe(ctx, repository, branch, key, nil)
		}
```

or just 
```suggestion
          err := g.safeBranchWrite(ctx, log, repository, branchID,
		safeBranchWriteOptions{}, func(branch *Branch) error {
			return g.deleteUnsafe(ctx, repository, branch, key, nil)
		})
```

2023-06-26 07:19 UTC, itaiad200 commented on pkg/graveler/graveler.go
> +	g.monitorRetries(ctx, retries, repository.RepositoryID, branchID, "revert")
Same here

2023-06-26 07:19 UTC, itaiad200 commented on pkg/graveler/graveler.go
> +	g.monitorRetries(ctx, retries, repository.RepositoryID, branchID, "delete")
Mostly worried about adding `safeBranchWrite` in the future without monitoring the retries.

2023-06-26 08:13 UTC, N-o-Z reviewed
We don't have a general retry operation context, which causes us to have several replicated retry logic as @itaiad200 stated. We can easily miss logging retry operations this way, one example is retryRepoMetadataUpdate. I understand that this PR focuses mainly on the branch update retry mechanism, but since the title of the PR says "monitor retries during Graveler operations" I thought this is worth a mention

2023-06-26 08:33 UTC, arielshaqed reviewed
Thanks; PTAL!

2023-06-26 08:51 UTC, itaiad200 approved these changes
LGTM

2023-06-26 09:06 UTC, arielshaqed commented
Thanks!

Pulling as soon as GitHub actions notices that GitHub actions have succeeded.

2023-06-28 10:45 UTC, arielshaqed commented
> We don't have a general retry operation function, which causes us to have several replicated retry logics as @itaiad200 stated. We can easily miss logging retry operations this way, one example is retryRepoMetadataUpdate. I understand that this PR focuses mainly on the branch update retry mechanism, but since the title of the PR says "monitor retries during Graveler operations" I thought this is worth a mention

Unfortunately each retry is subtly different.  We should probably collect more context about what we _want_ each to do and then refactor.  (For instance, we don't always back off!)

2023-06-28 10:58 UTC, merged