remove docs for spark2
treeverse/lakeFS pull request #6183
Opened 2023-07-11 08:44 UTC by johnnyaug

### Linked Issue

Closes #(Insert issue number closed by this PR)

---

## Change Description

### Background

Share context and relevant information for the PR: offline discussions, considerations, design decisions etc.

### Bug Fix

1. Problem - The reason for opening the bug
2. Root cause - Discovered root cause after investigation
3. solution - How was the bug fixed
      
### New Feature

Description of new feature

### Testing Details

How were the changes tested?
Added new unit tests / integration tests

### Breaking Change?

Does this change break any existing functionality? (API, CLI, Clients)

---

## Additional info

Logs, outputs, screenshots of changes if applicable (CLI / GUI changes)

---

### Contact Details

How can we get in touch with you if we need more info? (ex. email@example.com)

2023-07-11 09:21 UTC, rmoff commented
I don't have sufficient context/knowledge to comment on the removal of support for Spark 2, so will leave that to other reviewers. 
In terms of the docs should we call out that Spark 2 is not supported (vs just omitting mention of it)?

2023-07-12 09:27 UTC, rmoff requested changes
In terms of the docs should we call out that Spark 2 is not supported (vs just omitting mention of it)?

2023-07-12 10:08 UTC, johnnyaug commented
@rmoff, done.

2023-07-12 10:13 UTC, arielshaqed approved these changes
Neat, thanks!

Please open an issue to discuss whether we should get rid of the "2.12" flavour of the JAR: it might no longer be needed!  (But not clear because maybe we'll need it in future, when _another_ Spark version bumps their Scala runtime version???)

2023-07-12 14:55 UTC, rmoff requested changes
i've added some suggested wording

2023-07-12 14:55 UTC, rmoff commented on docs/reference/spark-client.md
> +
```suggestion
Please note that Spark 2 is no longer supported with the lakeFS metadata client.
{: .note }

```

2023-07-12 14:55 UTC, rmoff commented on clients/spark/README.md
>  ## Installation
```suggestion
Please note that Spark 2 is no longer supported with the lakeFS client.
{: .note }

## Installation
```

2023-07-12 15:10 UTC, merged