Remove callout-related CSS
treeverse/lakeFS pull request #6219
Opened 2023-07-17 14:33 UTC by johnnyaug

After adding callouts feature, this is no longer needed.
Note: this turns all existing notes to blue color.

2023-07-17 14:37 UTC, rmoff requested changes
Nice catch @johnnyaug. 

IMHO we should keep the colour customisation though (I'm not sure if it's through a different CSS route or not) - the existing colours I think fit much better than the default blue. 

![CleanShot_2023-07-17_at_15 35 30](https://github.com/treeverse/lakeFS/assets/3671582/7c926f77-6f90-4c8b-91f1-fba61b2f9699)

![image](https://github.com/treeverse/lakeFS/assets/3671582/f4dcb20a-4419-4fc6-8407-dd37e5a27836)

2023-07-18 11:23 UTC, johnnyaug commented
@rmoff done

2023-07-19 08:29 UTC, rmoff commented
@johnnyaug I've pushed a change to bring the style closer to what it is at the moment.

2023-07-19 08:30 UTC, rmoff approved these changes

2023-07-20 10:23 UTC, merged