Task/lakectl local list 6281
treeverse/lakeFS pull request #6302
Opened 2023-08-02 07:45 UTC by N-o-Z

### Linked Issue

Closes #6281

---

## Change Description

### Background

Implement lakectl local command which lists all folders linked to lakefs paths

### Bug Fix

1. Problem - The reason for opening the bug
2. Root cause - Discovered root cause after investigation
3. solution - How was the bug fixed
      
### New Feature

Part of task https://github.com/treeverse/lakeFS/issues/6241

### Testing Details

Unit testing for tools, lakectl tests will be added for esti upon feature completion

### Breaking Change?

No

---

2023-08-02 20:32 UTC, nopcoder requested changes
Added some comments about the code.
What is the use case of this command?
Was expected that we will have a command that will accept or use the current directory and lookup (in path or parents) for our yaml file and dump the information. Command like: lakectl local show.
Using find (command like utility) and lakectl local show I can run something like this list command.

2023-08-03 08:04 UTC, N-o-Z commented on cmd/lakectl/cmd/local_list.go
> +					"Last synced HEAD",
I think the ref is too general. Should be either head or commit. WDYT?

2023-08-03 08:07 UTC, N-o-Z commented on pkg/git/git.go
> +	}
There are 2 types of errors we would like to specifically distinguish from which are the environment doesn't support git, and the current working directory is not a git repository.

2023-08-03 08:10 UTC, N-o-Z commented
> Added some comments about the code. What is the use case of this command? Was expected that we will have a command that will accept or use the current directory and lookup (in path or parents) for our yaml file and dump the information. Command like: lakectl local show. Using find (command like utility) and lakectl local show I can run something like this list command.

This is basically the same functionality you described. When given a linked directory it will act exactly as 'show', and when providing a parent dir it will find all linked directories under that path

2023-08-03 10:59 UTC, nopcoder commented on pkg/git/git.go
> +	}
You added lookup for git - so in the case we found git - we left only with the fact that that we have git tool and it didn't recognize a git repository.

2023-08-03 12:15 UTC, nopcoder approved these changes
LGTM - I'll move my functional comment to the design document.
Added comment in `ReadIndex` and optional suggestion for the column name.

2023-08-03 12:15 UTC, nopcoder commented on pkg/local/index.go
> +	idx.root = filepath.Dir(idxPath)
move after the err check

2023-08-03 14:47 UTC, N-o-Z commented on pkg/git/git.go
> +	}
Remove the generic GitError

2023-08-03 15:01 UTC, merged