Implement lakectl local clone
treeverse/lakeFS pull request #6320
Opened 2023-08-04 16:47 UTC by N-o-Z

### Linked Issue

Closes #6303

---

## Change Description

### Background

Implement lakectl local command which inits and downloads contents from lakefs path to a local directory
      
### New Feature

Part of task https://github.com/treeverse/lakeFS/issues/6241

### Testing Details

How were the changes tested?
Unit testing for tools, lakectl tests will be added for esti upon feature completion. SyncManager will be tested as part of the command (was tested manually)

### Breaking Change?

No

2023-08-08 07:12 UTC, guy-har requested changes
Nice! looks good
Added mostly suggestions, requesting changes due to the fact we can get stuck waiting on the error channel

2023-08-08 07:26 UTC, N-o-Z commented on pkg/uri/parser.go
> +}
Add documentation and made it a member function

2023-08-08 07:27 UTC, N-o-Z commented on cmd/lakectl/cmd/local_clone.go
> +	Short: "init local directory and download objects from lakeFS path",
How about "Clone a path from a lakeFS repository into a new directory."?

2023-08-08 07:33 UTC, guy-har commented on pkg/local/sync.go
> +func (s *SyncManager) Sync(rootPath string, remote *uri.URI, changeSet <-chan *Change) error {
Can you please Document this method?

2023-08-08 07:34 UTC, guy-har commented
Another thing I noticed is that the clone command fails when running on a branch with uncommitted changes

2023-08-08 07:42 UTC, N-o-Z commented on cmd/lakectl/cmd/local_clone.go
> +		force := Must(cmd.Flags().GetBool("force"))
Done

2023-08-08 07:44 UTC, N-o-Z commented on cmd/lakectl/cmd/local_clone.go
> +					DieErr(fmt.Errorf("%w: HTTP %d", err, listResp.StatusCode()))
Fixed

2023-08-08 08:09 UTC, N-o-Z commented on pkg/local/sync.go
> +func (s *SyncManager) Sync(rootPath string, remote *uri.URI, changeSet <-chan *Change) error {
Done and refactored

2023-08-08 08:12 UTC, N-o-Z commented on pkg/local/sync.go
> +			}
Done

2023-08-08 12:09 UTC, guy-har commented
@N-o-Z, another thing I'm concerned about is:
What do we expect to happen in case of failure (e.g. CTRL-C after a while)?
Currently, it's resulted in corrupted data without any way to identify it's a corrupted state, it just looks like we did some local changes. Maybe we should delete in case of failure, WDYT?

2023-08-08 13:15 UTC, N-o-Z commented on pkg/local/sync.go
> +		}
Done

2023-08-08 13:21 UTC, N-o-Z commented on pkg/local/progress.go
> +
progress.Writer is the progress pool AFAIK. We wrapped the trackers in order to provide additional functionality (e.g. ProgressUpdaterReader)

2023-08-08 13:38 UTC, N-o-Z commented
> @N-o-Z, another thing I'm concerned about is: What do we expect to happen in case of failure (e.g. CTRL-C after a while)? Currently, it's resulted in corrupted data without any way to identify it's a corrupted state, it just looks like we did some local changes. Maybe we should delete in case of failure, WDYT?

Thanks, 
I'm not sure we want to complicate things by creating an "revert sync" flow.
I will open a separate issue to deal with interrupts for all local commands and provide a meaningful error message, similarly to what we did in import.

2023-08-09 10:05 UTC, guy-har approved these changes

2023-08-09 10:05 UTC, guy-har commented on pkg/local/sync.go
>  func (s *SyncManager) Sync(rootPath string, remote *uri.URI, changeSet <-chan *Change) error {
I have a confession:
I asked chatGPT if he can improve the documentation. Expected it to make slight changes, got a bit more than 
that, but I had to put it out here:

```
// Sync synchronizes changes between a local directory and a remote URI.
// The function consumes changes provided through the changeSet channel.
// Depending on the type and source of each change, the Sync function will
// either download, upload, or delete the associated content.
// 
// Parameters:
// - rootPath: The local directory path that should be kept in sync with the remote.
// - remote: The URI representing the remote directory.
// - changeSet: A channel through which changes to be synchronized are sent.
//
// The function leverages goroutines for parallel processing of changes, and the 
// maximum number of parallel operations is determined by s.maxParallelism. The synchronization 
// process is stopped early if an error is encountered.
// 
// After syncing, any empty directories within rootPath are pruned.
// 
// Returns:
// - nil if the sync completes successfully.
// - An error if any operation during the sync or pruning process fails.
```
It isn't aligned with our documentation, so I'm not sure what I'd suggest, but still needed to share 🤷

2023-08-09 10:19 UTC, merged