Fix cosmosdb pagination bug
treeverse/lakeFS pull request #6336
Opened 2023-08-07 12:15 UTC by itaiad200

closes #6346 6346

2023-08-07 13:16 UTC, N-o-Z requested changes
Nothing about the code:
1. How does the bug manifests?
2. Can we link a an issue to this PR?
3. Can we add a unit test to catch this scenario?

2023-08-08 11:36 UTC, itaiad200 commented
> Nothing about the code:
> 
> 1. How does the bug manifests?
> 2. Can we link a an issue to this PR?
> 3. Can we add a unit test to catch this scenario?

Thanks, fixed all of the above. Added a test and tested locally against a live CosmosDB account.

2023-08-09 09:47 UTC, N-o-Z commented on pkg/kv/kvtest/store.go
> +		}
```suggestion
		require.NoError(t, scan.Err(), "scan ended with an error")
```

2023-08-09 09:48 UTC, N-o-Z approved these changes
Thanks, approved with 2 suggestions (always prefer one liners 😄 )

2023-08-09 11:13 UTC, merged