Task/add lakectl local pull tests 6380
treeverse/lakeFS pull request #6383
Opened 2023-08-13 12:43 UTC by N-o-Z

Closes #6380

2023-08-13 19:04 UTC, nopcoder requested changes

2023-08-13 19:04 UTC, nopcoder commented on esti/lakectl_local_test.go
> +				return slices.Contains(deleted, s)
The deleted is one item - it means we don't need a slice of `deleted` as the code also run a single command and reference `deleted[0]`.
So having when we delete the item from the slice we can just:
```suggestion
				return s == deleted
```

2023-08-14 07:16 UTC, N-o-Z commented on esti/lakectl_local_test.go
> +			vars["PREFIX"] = "/" + tt.prefix
There's some setup code that's running before the tests and requires the values. I don't feel this is necessary

2023-08-14 07:26 UTC, N-o-Z commented on cmd/lakectl/cmd/local_checkout.go
> +	fmt.Printf("Checkout Summary:\nDownloaded:%d\nRemoved:%d\n", summary.Downloaded, summary.Removed)
I'll add colors in a different PR

2023-08-14 07:47 UTC, nopcoder commented on esti/lakectl_local_test.go
> +			vars["PREFIX"] = "/" + tt.prefix
Except repo, storage and branch the setup code doesn't provide extra information for the vars.

2023-08-14 07:47 UTC, nopcoder approved these changes
LGTM!

2023-08-14 08:11 UTC, merged