Add default configs section with default host
treeverse/lakeFS pull request #650
Opened 2020-09-25 14:28 UTC by eylonronen

Solves #649

2020-09-25 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=650) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=650) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=650) it.</sub>

2020-09-27 08:58 UTC, johnnyaug requested changes
Hi @eylonronen!
Welcome and thank you for your effort and this PR.
See minor change request

2020-09-27 08:58 UTC, johnnyaug commented on cmd/lakectl/cmd/root.go
> +	//Configuration defaults
```suggestion
	// Configuration defaults
```

2020-09-27 08:58 UTC, johnnyaug commented on cmd/lakectl/cmd/root.go
> +	viper.SetDefault("server.endpoint_url", "http://127.0.0.1:8000")
Note that server.endpoint_url is already defined as a constant at the top of this file.
I think the value itself could also go as a separate constant, "DefaultServerEndpointURL".

2020-10-01 09:58 UTC, closed without merging

2020-10-01 13:15 UTC, guy-har reviewed
looks good 👍