lakectl: deprecate dbt and metastore commands
treeverse/lakeFS pull request #6565
Opened 2023-09-07 16:08 UTC by nopcoder

Close https://github.com/treeverse/lakeFS/issues/6564

2023-09-10 08:51 UTC, itaiad200 commented
I think that the integration pages should help clarify the current situation: These command are deprecated and would be removed soon. A better, automated integration will replace them.

2023-09-10 08:51 UTC, itaiad200 approved these changes
LGTM

2023-09-10 21:10 UTC, nopcoder commented
@itaiad200 please review the documentation changes

2023-09-11 07:44 UTC, itaiad200 requested changes

2023-09-11 07:44 UTC, itaiad200 commented on docs/integrations/glue_hive_metastore.md
> +**Deprecated Feature:** This feature is being phased out. A superior replacement will be introduced soon.
These warnings are vague and don't give confidence that we'll continue to support these integrations. 
```suggestion
**Deprecated Feature:** Having heard the feedback from the community, we are planning to replace the below manual steps with an automated process. You can read more about it [here](https://github.com/treeverse/lakeFS/issues/6461).
```

2023-09-11 07:44 UTC, itaiad200 commented on docs/integrations/glue_hive_metastore.md
> +**Deprecated Feature:** This feature is being phased out. A superior replacement will be introduced soon.
Here and elsewhere

2023-09-11 08:07 UTC, itaiad200 approved these changes
LGTM

2023-09-11 08:16 UTC, merged