Remove update and forgot password APIs
treeverse/lakeFS pull request #6591
Opened 2023-09-13 10:46 UTC by idanovo

Closes #[(Insert issue number closed by this PR)](https://github.com/treeverse/lakeFS/issues/6532)

2023-09-13 12:08 UTC, arielshaqed approved these changes
Neat, thanks!

* login.tsx needs some care, GitHub Actions / Analyze says maybe the `getAuthCapabilities()` call is unused.

2023-09-13 12:08 UTC, arielshaqed commented on api/swagger.yml
> +          description: a unique identifier for the user.
Nice catch! ✨

2023-09-13 12:10 UTC, arielshaqed requested changes
Forgot, so blocking for now

**ALSO** please go over webui/ and look for these URLs: webui doesn't use a generated client but _did_ use these URLs, so needs to be changed manually and the TypeScript compiler cannot find the change from the OpenAPI spec change.

2023-09-13 12:17 UTC, idanovo commented
> Forgot, so blocking for now
> 
> **ALSO** please go over webui/ and look for these URLs: webui doesn't use a generated client but _did_ use these URLs, so needs to be changed manually and the TypeScript compiler cannot find the change from the OpenAPI spec change.

@arielshaqed Not sure I understand this comment. I removed the calls for update/forgot password from the webui code.
Am I missing anything?

2023-09-14 06:44 UTC, arielshaqed commented
> > Forgot, so blocking for now
> > **ALSO** please go over webui/ and look for these URLs: webui doesn't use a generated client but _did_ use these URLs, so needs to be changed manually and the TypeScript compiler cannot find the change from the OpenAPI spec change.
> 
> @arielshaqed Not sure I understand this comment. I removed the calls for update/forgot password from the webui code. Am I missing anything?

Nope, you're right and I'm wrong.

THANKS!

2023-09-14 06:45 UTC, arielshaqed approved these changes
Love the diff stats!
![GitHub shows 22 lines "added", 2454 **removed**](https://github.com/treeverse/lakeFS/assets/7802932/198cdc84-d970-4d2c-8764-3342ae8ceca1)

2023-09-14 07:31 UTC, merged