Fix/6584 content type for lakectl local
treeverse/lakeFS pull request #6644
Opened 2023-09-23 10:22 UTC by 0x-chaitu

Closes #6584 

## Change Description

### Background

Followed code from lakectl fs upload.

### Bug Fix

If this PR is a bug fix, please let us know about:

1. Problem - lakectl local didnt support --content-type flag.
3. Solution - added content-type support

### Testing Details

How were the changes tested?

They were tested by running lakectl local to upload files with content-type flag

### Contact Details

chaitubhojane@gmail.com

2023-09-23 16:27 UTC, itaiad200 requested changes
Hey @0x-chaitu - thank you for your efforts. We value every contribution to this project, it's all about the community :)

Regarding the code, notice that unlike `lakectl fs upload ...`, `lakectl local commit ...` may upload many objects with different content types at once. When the user request for it explicitly using a flag, we should identify the content automatically and not rely on a single given content that cannot fit all types. Other than that, the PR looks very promising.

2023-09-24 03:57 UTC, 0x-chaitu commented
Thanks @itaiad200, 
Yes I will add --include-content-type flag with the automation.

2023-09-28 14:39 UTC, arielshaqed requested changes
I don't understand what the `--content-type` flag does.  AFAICT it gives the _same_ content type to all objects in my commit.  Can you give a use-case for why this would be useful?

2023-09-28 14:39 UTC, arielshaqed commented on cmd/lakectl/cmd/local_commit.go
> +	localIncludeContentTypeFlagName = "include-content-type"
```suggestion
	localIncludeContentTypeFlagName = "detect-content-type"
```

2023-09-28 14:39 UTC, arielshaqed commented on cmd/lakectl/cmd/local_commit.go
> +		err = s.Sync(idx.LocalPath(), remote, c, contentType, includeContentType)
I don't understand.  When would I want to set contentType to the _same_ value on all the files in a Sync?

2023-09-28 14:39 UTC, arielshaqed commented
# THANKS

for picking up this issue and working to fix it.  This is really appreciated, and a great way to improve lakeFS as a product.

2023-10-25 21:39 UTC, nopcoder commented
Hi @0x-chaitu, could you please provide an update on the PR status?

2023-10-26 07:02 UTC, 0x-chaitu commented
> Hi @0x-chaitu, could you please provide an update on the PR status?

Hi @nopcoder, @itaiad200 has self-assigned the issue.

2023-10-26 08:01 UTC, itaiad200 commented
Hey @0x-chaitu , I self-assigned the PR so I could track this better. We do that normally for all contributors. Do you still intend to work on this PR or should we take it?

2023-11-08 14:57 UTC, 0x-chaitu commented
Hey, @itaiad200 Please take it.

2023-12-16 01:49 UTC, closed without merging