New line
treeverse/lakeFS pull request #6650
Opened 2023-09-26 15:22 UTC by idanovo

Closes #6321

2023-09-27 13:27 UTC, N-o-Z requested changes
Overall looks good.
I'd like to raise 2 fundamental issues which might require a product discussion:
1. We might want to consider consolidating the single / recursive flows and use the sync manager in both + removing the recursive flag
2. We should take advantage of the parallelism of the sync manager and introduce this parameter in the upload command + use the default value
3. The sync manager provides a summary of the performed operations - we should use this as the output for the commands (you can see examples of usage in the local commands)

2023-09-27 13:27 UTC, N-o-Z commented on cmd/lakectl/cmd/fs_download.go
>  		recursive := Must(flagSet.GetBool("recursive"))
Also we might want to move the parallel check ( <1 ) to `getLocalSyncFlags`

2023-09-27 13:27 UTC, N-o-Z commented on cmd/lakectl/cmd/fs_download.go
> +		if recursive {
Valid flow also for !recursive
We should probably eliminate this param

2023-09-27 13:27 UTC, N-o-Z commented on pkg/local/sync.go
> +func (s *SyncManager) Download(ctx context.Context, rootPath string, remote *uri.URI, path string) error {
Not we really need to externalize the Download and Upload methods

2023-09-27 13:27 UTC, N-o-Z commented on pkg/local/sync.go
> +			// we wrote something, Upload it!
Revert

2023-09-27 13:27 UTC, N-o-Z commented on pkg/local/sync.go
> +			if err := s.Download(ctx, rootPath, remote, change.Path); err != nil {
👍🏽 on `change.Path`

2023-09-27 14:56 UTC, idanovo commented
> Overall looks good. I'd like to raise 2 fundamental issues which might require a product discussion:
> 
> 1. We might want to consider consolidating the single / recursive flows and use the sync manager in both + removing the recursive flag
> 2. We should take advantage of the parallelism of the sync manager and introduce this parameter in the upload command + use the default value
> 3. The sync manager provides a summary of the performed operations - we should use this as the output for the commands (you can see examples of usage in the local commands)

@N-o-Z 
My main concern with 1 and 2 is that the sync manager currently works with directories, which means I'll have to add some complexity to use the apply/sync methods to upload/download a specific file.
This is why preferred to use Download/Upload methods where I could

2023-09-28 06:16 UTC, idanovo commented on cmd/lakectl/cmd/fs_download.go
>  		preSignMode := Must(flagSet.GetBool("pre-sign"))
can't use it as it uses pre-signed as true by default

2023-10-01 16:51 UTC, N-o-Z commented on cmd/lakectl/cmd/fs_download.go
>  		preSignMode := Must(flagSet.GetBool("pre-sign"))
We might want to change that to be true by default, maybe @ozkatz can comment on that

2023-10-01 16:53 UTC, N-o-Z approved these changes
Approving changes pending @ozkatz response - I do believe we should change the default behavior to `pre-sign=true`

2023-10-01 17:02 UTC, idanovo commented on cmd/lakectl/cmd/fs_download.go
>  		preSignMode := Must(flagSet.GetBool("pre-sign"))
I think it will be a better thing to do it in a different PR especially because [this](https://github.com/treeverse/lakeFS/issues/6426) issue

2023-10-01 17:04 UTC, merged