Python Wrapper: Add skip workflow on required
treeverse/lakeFS pull request #7087
Opened 2023-11-30 10:40 UTC by N-o-Z

Closes #7086

2023-11-30 13:06 UTC, nopcoder requested changes

2023-11-30 13:06 UTC, nopcoder commented on .github/workflows/python-wrapper-unit-tests.yaml
1. Can we keep it one job? and make the step optional? 
2. Filter should consider changes in this python workflow.

2023-12-01 09:28 UTC, N-o-Z commented on .github/workflows/python-wrapper-unit-tests.yaml
1. Making it a single job will require putting conditions on each and every step - I don't like this idea
2. Done

2023-12-01 09:29 UTC, nopcoder approved these changes
lgtm

2023-12-01 09:54 UTC, merged