fix client is None
treeverse/lakeFS pull request #7097
Opened 2023-12-01 09:10 UTC by d710055071

Closes #(Insert issue number closed by this PR)

## Change Description
`
def get_client():
    from lakefs.client import Client
    clt = Client(username=username, password=password, host=host)
    return clt

# 获取链接
clt = get_client()
# 仓库
repo = lakefs.Repository(repository_id="datalab",client=clt)
# 分支
ref = repo.ref(ref_id="main")
# 对象
stored_object = ref.object(path="coco/coco128.zip")
# 文件对象
fd = stored_object.reader()

# 文件操作
# 没有参数直接读取整个文件
filedata = fd.read()
save_obj = open("coco128.zip","wb")
save_obj.write(filedata)
save_obj.close()
`

### Background

(dinov2) dongzf@dongzf-LEGION-REN7000P-26AMR:/mnt/sda/code/lakeFS-master$  cd /mnt/sda/code/lakeFS-master ; /usr/bin/env /home/dongzf/miniconda3/envs/dinov2/bin/python /home/dongzf/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 50565 -- /mnt/sda/code/lakeFS-master/clients/python-wrapper/study.py 
Traceback (most recent call last):
  File "/home/dongzf/miniconda3/envs/dinov2/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dongzf/miniconda3/envs/dinov2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dongzf/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/dongzf/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/dongzf/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/dongzf/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/dongzf/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/dongzf/.vscode/extensions/ms-python.python-2023.20.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/mnt/sda/code/lakeFS-master/clients/python-wrapper/study.py", line 28, in <module>
    fd = stored_object.reader()
  File "/mnt/sda/code/lakeFS-master/clients/python-wrapper/lakefs/object.py", line 564, in reader
    return ObjectReader(self, mode=mode, pre_sign=pre_sign, client=self._client)
  File "/mnt/sda/code/lakeFS-master/clients/python-wrapper/lakefs/object.py", line 209, in __init__
    super().__init__(obj, mode, pre_sign, client)
  File "/mnt/sda/code/lakeFS-master/clients/python-wrapper/lakefs/object.py", line 75, in __init__
    self._pre_sign = pre_sign if pre_sign is not None else client.storage_config.pre_sign_support
AttributeError: 'NoneType' object has no attribute 'storage_config'
### Bug Fix

If this PR is a bug fix, please let us know about:

1. Problem - The reason for opening the bug
2. Root cause - Discovered root cause after investigation
3. Solution - How the bug was fixed
      
### New Feature

If this PR introduces a new feature, describe it here.

### Testing Details

How were the changes tested?

### Breaking Change?

Does this change break any existing functionality? (API, CLI, Clients)

## Additional info

Logs, outputs, screenshots of changes if applicable (CLI / GUI changes)

### Contact Details

How can we get in touch with you if we need more info? (ex. email@example.com)

2023-12-03 21:07 UTC, N-o-Z commented
@d710055071 Thank you for the contribution and nice catch!
Can you please sign the CLA - in order to contribute to the project

2023-12-04 09:31 UTC, d710055071 commented
This is the first line of code I have contributed to the open source community. Thank you very much

2023-12-05 08:23 UTC, N-o-Z requested changes
Thank you @d710055071 looks good.
One lint comment

2023-12-05 08:23 UTC, N-o-Z commented on clients/python-wrapper/lakefs/reference.py
> +        return StoredObject(self._repo_id, self._id, path,self._client)
```suggestion
        return StoredObject(self._repo_id, self._id, path, self._client)
```

2023-12-06 00:53 UTC, d710055071 commented on clients/python-wrapper/lakefs/reference.py
> +        return StoredObject(self._repo_id, self._id, path,self._client)
Thank you very much for your prompt

2023-12-06 07:51 UTC, N-o-Z approved these changes
LGTM!

2023-12-06 08:14 UTC, merged