Improve documentation of "create tag" API
treeverse/lakeFS pull request #7112
Opened 2023-12-04 14:17 UTC by arielshaqed

Closes #7103.

2023-12-04 14:36 UTC, N-o-Z requested changes
The ref description felt a little bit confusing

2023-12-10 09:03 UTC, arielshaqed reviewed
Thanks!  PTAL...

2023-12-10 09:03 UTC, arielshaqed commented on api/swagger.yml
> +          description: reference to commit to tag
Changed to something shorter & I hope better.

2023-12-10 09:06 UTC, N-o-Z approved these changes

2023-12-10 09:09 UTC, arielshaqed commented
Thanks!

[![J. L. Picard: Enable autosquish!](https://github.com/treeverse/lakeFS/assets/7802932/9aed3a39-60e0-476e-8683-710a0344bb9e)](https://imgflip.com/i/88uoim)

2023-12-10 09:17 UTC, merged