Python Wrapper: Add ID field to repository model
treeverse/lakeFS pull request #7124
Opened 2023-12-06 16:23 UTC by ozkatz

Use case:

```python
for repo in lakefs.repositories():
    print(repo.id)
```
And getting back useful information - otherwise, holding a Repository instance doesn't provide a way to know **which** repository this is.

2023-12-06 16:26 UTC, nopcoder requested changes

2023-12-06 16:43 UTC, N-o-Z requested changes
Why is accessing the id via the properties not an option?

2023-12-07 18:23 UTC, ozkatz commented on clients/python-wrapper/lakefs/repository.py
> +        return f'Repository(id="{self.id}")'
Either the SDK supports using URIs or it doesn't.. only returning them without being able to use them feels inconsistent IMO

2023-12-09 16:50 UTC, nopcoder approved these changes
LGTM!

2023-12-09 18:06 UTC, N-o-Z approved these changes
Thanks!

2023-12-10 07:55 UTC, merged