catch when there are no changes in revert
treeverse/lakeFS pull request #7308
Opened 2024-01-18 14:15 UTC by lynnro314

close #6917

2024-01-23 12:33 UTC, nopcoder requested changes

2024-01-23 12:33 UTC, nopcoder commented on api/swagger.yml
> +          description: allow reverts without any changes
allow empty commit (revert without changes)

2024-01-23 12:33 UTC, nopcoder commented on cmd/lakectl/cmd/branch_revert.go
> +	allowEmptyRevert     = "allow-empty-revert"
allow-empty-commit?

There are two situations where we might want to allow empty commits: during regular commits and during reverts. I propose that we keep it the same.

What do you think?

2024-01-23 12:33 UTC, nopcoder commented on cmd/lakectl/cmd/branch_revert.go
> +	branchRevertCmd.Flags().Bool(allowEmptyRevert, false, "allow revert with no changes")
same here as part of the description where we instruct that we allow empty commit as part of the revert operation.

2024-01-23 12:33 UTC, nopcoder commented on pkg/catalog/catalog.go
> +	AllowEmpty   bool // allow revert with no changes
also here: allow empty commit

2024-01-23 12:33 UTC, nopcoder commented on pkg/graveler/graveler.go
> +		}
ErrNoChanges ?

2024-01-24 08:00 UTC, arielshaqed approved these changes
This is great, thanks!

One worry is that we _really_ want to test this.

* If there **is** a unit test for revert, please add a test for "no changes". 
* If tests for revert are entirely missing, please open an issue to test it
* If we have no tests _and_ already have an issue, then we just need to prioritize it...

2024-02-06 22:20 UTC, nopcoder requested changes
Minor comments to fix. Also there is a comment ariel added I don't think it was addressed.

2024-02-06 22:20 UTC, nopcoder commented on cmd/lakectl/cmd/branch_revert.go
> +	allowEmptyRevert     = "allow-empty-commit"
we have `allowEmptyCommit` you can use

2024-02-06 22:20 UTC, nopcoder commented on pkg/graveler/graveler.go
> +		if (metaRangeID == branchCommit.MetaRangeID) && !commitParams.AllowEmpty {
Missed this one in previs PR - we can't check the return value before we verified the error first.

2024-02-07 12:59 UTC, nopcoder approved these changes
LGTM!

2024-02-07 13:02 UTC, lynnro314 commented
Checked the timeout error on docs:
`[TIMEOUT] [https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id](https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id) | Timeout`
The link seems fine, so merging assuming the timeout is temporary. 

Also issue for adding unit test for revert: #7445

2024-02-07 13:02 UTC, merged