Unconditionally assign body in ServerException constructor
treeverse/lakeFS pull request #7315
Opened 2024-01-21 10:47 UTC by nicholasjng

Previously, in case a non-empty body was returned, the `body` field of `ServerException` would be undefined in case of a JSON body parsing error. The same would occur if body is None, since that branch avoids setting the `self.body` field entirely.

Consequently, the `ServerException.__str__()` method, which unconditionally accesses `self.body`, fails if a non-JSON-parseable (or None) body was given to the constructor.

The fix is to assign an empty dict as per the class attribute type hints in the two cases, so that the `ServerException.body` field is defined in any case.

### Background

We observed this in https://github.com/aai-institute/lakefs-spec/issues/255, and first thought this was our error handling code, but it turns out to be the mentioned assignment problem in the lakefs wrapper.

A follow-up question is why the lakeFS API does not return a JSON body at all in that case (attempting to overwrite a file on a protected branch).

2024-01-21 14:49 UTC, arielshaqed requested changes
Hi @nicholasjng ,

I do _not_ believe that this fix is appropriate: it loses the distinction between no body and valid-but-empty body.  If the issue is that `ServerException.__str__` breaks when there is no body, then I prefer to fix that function!

2024-01-21 16:11 UTC, nicholasjng commented
@arielshaqed But then, shouldn't the interface typing change? The distinction you mentioned does not appear there:

https://github.com/treeverse/lakeFS/blob/9dc6ed41f9dbcb9b0a106abc4cb0a6ed51bddf44/clients/python-wrapper/lakefs/exceptions.py#L23-L25

(If I understood correctly: `body=None` for no body, `body={}` for empty/unparseable body?)

2024-02-04 20:55 UTC, arielshaqed approved these changes
Thanks!  Giving the typing that you showed, I guess this fix makes sense.  If we decide to make the exception more informative we know what to do.  Until then the new code is _very much_ better, so not point in blocking further.

2024-02-06 08:00 UTC, arielshaqed commented
Remaining tests not relevant to Python wrapper, pulling by force.

2024-02-06 08:01 UTC, merged