Add wrapper to run lakeFS containers in integration tests
treeverse/lakeFS pull request #7329
Opened 2024-01-22 14:12 UTC by arielshaqed

2024-01-23 08:44 UTC, idanovo requested changes
I think we should get the lakeFS version from configuration

2024-01-23 08:44 UTC, idanovo commented on pkg/dockertest/lakefs_container.go
> +		}
```suggestion
		return  helpers.HTTPResponseAsError(res)
```

2024-01-23 08:44 UTC, idanovo commented on pkg/dockertest/lakefs_container.go
> +	Tag string
```suggestion
	DockerTag string
```
To avoid confusion with lakeFS tags

2024-01-23 08:44 UTC, idanovo commented on pkg/dockertest/lakefs_container.go
> +		// Don't forget to turn off stats!!
?

2024-01-23 08:44 UTC, idanovo commented on pkg/dockertest/lakefs_container_test.go
> +	const version = "1.9.1"
I think we should get it from configuration, no?

2024-01-23 09:40 UTC, nopcoder requested changes

2024-01-23 09:40 UTC, nopcoder commented on pkg/dockertest/lakefs_container_test.go
> +	lakefs_ci "github.com/treeverse/lakefs/pkg/dockertest"
lakefs_ci? can we keep it dockertest?

2024-01-23 09:40 UTC, nopcoder commented on pkg/dockertest/lakefs_container_test.go
> +	}
Use Fatal - if we continue to fall we will get panic on using nil

2024-01-23 09:40 UTC, nopcoder commented on pkg/dockertest/lakefs_container_test.go
> +	container := lakefs_ci.New().WithTag(version).New(ctx, t, pool)
defer Close after this one?

2024-01-23 09:40 UTC, nopcoder commented on pkg/dockertest/lakefs_container.go
> +	}()
do we like to have this defer after we successfully call RunWithOptions?

2024-01-24 15:25 UTC, idanovo approved these changes
Thanks, LGTM

2024-01-24 21:29 UTC, nopcoder approved these changes
LGTM!

2024-01-24 21:29 UTC, nopcoder commented on pkg/dockertest/lakefs_container_test.go
> +	lakefs_ci "github.com/treeverse/lakefs/pkg/dockertest"
forgot that this is testing the test code

2024-01-25 08:24 UTC, arielshaqed commented
> forgot that this is testing the test code

![Testing the test code](https://github.com/treeverse/lakeFS/assets/7802932/690ab753-955a-4a40-8103-f0aac7588ff7)

2024-01-25 08:24 UTC, arielshaqed commented
THANKS!

2024-01-25 08:24 UTC, merged