fixes #656
treeverse/lakeFS pull request #756
Opened 2020-10-03 17:23 UTC by indhupriya

Draft PR to test Nessie action

2020-10-03 17:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=756) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=756) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=756) it.</sub>

2020-10-12 07:18 UTC, itaiad200 commented on .github/workflows/nessie.yaml
> +            echo "Image doesnt exist"
Typo: doesn't

2020-10-12 07:19 UTC, itaiad200 requested changes
Tested it on my branch and it works. Great Job!
Please fix the minor typo and I'll approve.

2020-10-12 23:19 UTC, indhupriya commented on .github/workflows/nessie.yaml
> +            echo "Image doesnt exist"
Fixed the typo!

2020-10-13 06:50 UTC, itaiad200 approved these changes

2020-10-13 06:51 UTC, merged