Introduce support of GCS encryption for both CMEK and CSEK
treeverse/lakeFS pull request #7608
Opened 2024-03-27 17:46 UTC by emulatorchen

Closes #(Insert issue number closed by this PR)

## Change Description

### Background

Provide the support of GCS encryption for both CMEK and CSEK
      
### New Feature

Issue link: https://github.com/treeverse/lakeFS/issues/7557

- Configuration of CMEK supported
- Configuration of CSEK supported
- Throw an error for generating PreSignedURL of GCS with CSEK as the user must have the key in the configuration file
  - Frontend change is required
  - If user must have the key in configuration, then the CSEK make not much sense for PreSignedURL

### Testing Details

How were the changes tested?
* CMEK and CSEK cannot be configured at the same time, or the server will fail to start
* Upload the file with CMEK
* Check the content of the CMEK encrypted file with CMEK configured
* Upload the file with CSEK
* Check the content of the CMEK encrypted file with CMEK configured
* When the CSEK is configured and PreSignedURL is enabled, generating a PreSignedURL of a CSEK encrypted object is failed

### Breaking Change?

Does this change break any existing functionality? (API, CLI, Clients)

No breaking change as there's no API changed, only the server configuration is required

## Additional info

Logs, outputs, screenshots of changes if applicable (CLI / GUI changes)

### Contact Details

By GitHub  account

2024-03-27 17:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/treeverse/lakeFS?pullRequest=7608) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=7608) before we can accept your contribution.<br/><hr/>**Victor Chen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=7608) it.</sub>

2024-04-17 15:35 UTC, itaiad200 commented
Hey @emulatorchen , thank you for your contribution! I should of reviewed sooner, it took me a bit longer since I needed to ramp up my gcp/kms knowledge. @Jonathan-Rosenberg and myself were debating some CSEK/CMEK questions. As we're both not very familiar with gcp, I wonder if you could help us with answering the below:
1. What's the flow for key rotations for anyone of the 2 settings? We're obviously very worried about user's data that becomes inaccessible due to a rotation taking place, but it's not just data. lakeFS stores immutable committed metadata in the object store using the same gs adapter we're modifying, so a rotation that goes wrong could fail lakeFS completely.
2. Can the user set CSEK/CMEK after some time of using lakeFS? Will the previous saved objects be accessible.
3. Would you say it's a lakeFS-level setting? From what we understand, it's common for different gs buckets to have different encryption keys. A single lakeFS installation can manage multiple repositories across different buckets. What's the additional value lakeFS give to the user? It seems like we're forcing a single encryption key for all the repos. Isn't the user better off setting this in the bucket level and keep lakeFS unaware to encryption (again - not sure if that's possible).

2024-04-18 17:44 UTC, emulatorchen commented
> Hey @emulatorchen , thank you for your contribution! I should of reviewed sooner, it took me a bit longer since I needed to ramp up my gcp/kms knowledge. @Jonathan-Rosenberg and myself were debating some CSEK/CMEK questions. As we're both not very familiar with gcp, I wonder if you could help us with answering the below:
> 
> 1. What's the flow for key rotations for anyone of the 2 settings? We're obviously very worried about user's data that becomes inaccessible due to a rotation taking place, but it's not just data. lakeFS stores immutable committed metadata in the object store using the same gs adapter we're modifying, so a rotation that goes wrong could fail lakeFS completely.
> 2. Can the user set CSEK/CMEK after some time of using lakeFS? Will the previous saved objects be accessible.
> 3. Would you say it's a lakeFS-level setting? From what we understand, it's common for different gs buckets to have different encryption keys. A single lakeFS installation can manage multiple repositories across different buckets. What's the additional value lakeFS give to the user? It seems like we're forcing a single encryption key for all the repos. Isn't the user better off setting this in the bucket level and keep lakeFS unaware to encryption (again - not sure if that's possible).

Really appreciate the review! It's my honor to have those critical questions being addressed.

1. In short, rotating key in KMS does not effect existing objects, so
  a.  CSMK (Available only in bucket level)
    1. Using the version of the encrypted to decrypt
    2. Updating the key to the latest version request a new copy of the object, to my understanding it seems the same as S3
 b. CSEK (Available only in bucket level)
    1. Similar to CSMK, updating a key requires you to make a new copy

2. As explained above, anything happened in KMS level will be fine but if the key path or the key value must be changed by copying to a object, then either it is not possible to be done with existing implementation. So for CMEK we can still have the auto and manual in KMS way, not possible for changing key path in CMEK or key value in CSEK, the old object will not be available any more.

3. Yes and we also had thought about this before. There can be at least two perspectives of the encryption: Internal solution and Multi-Tenant.
  - Internal service: All the users are internal and most like in the same team so the point will be to ensure the data is encrypted and only be granted for specific accounts
  - Multi-tenant: Users are mostly from external and would like to manage their own encryption
And TBH we are more like in a hybrid way. So ideally we would like to have different key setup for each repository. 

The reason I am making it in lakeFS level is because there's already a S3 reference in the lakeFS level that I thought it will be easier for you to accept it so that we can meet the internal need first. Then I would like look for a possible solution as a multi-tenant proposal, and they should be able to exist in lakeFS just cannot be configured at the same time. But we all know that it will be more complicated, especially when we are providing an universal UI/API/CLI to the operation of different storage options, different keys will require not just the permission but also the key management in lakeFS itself or we may have issues in CSEK(ex. not able to preview in UI, similar reason I dropped the support of PreSignedURL when CSEK enabled) or the key of the bucket is not using the default key of the project.

And now I implementing CSEK is just providing an option, we will consider more on CMEK. The reason is that CMEK can actually be enabled almost without implementation in lakeFS as long as the key is the default key of the project and being proper authenticated. On the other hand, CSEK is more like a thing that user can have more control when there's risk happened. So the implementation is to consider the case we would like the CMEK being used as an internal protection for now, and I am happy to remove CSEK if you think it's risky.

2024-05-12 14:56 UTC, Jonathan-Rosenberg requested changes
Thanks you once more.
Since you introduce a new type that wraps another, the methods and functions should use this type instead of the wrapped one. I gave you some comments regarding that, but in general, since the methods of the wrapped struct (`storage.ObjectHandle`) can be called over the wrapping type, you can use the wrapping type only. This will create consistency and a single way of using the methods.

2024-05-12 14:56 UTC, Jonathan-Rosenberg commented on pkg/block/gs/adapter.go
> +*/
comments related to methods/functions in Go begin with the method/function's name. Please rephrase that.

2024-05-12 14:56 UTC, Jonathan-Rosenberg commented on pkg/block/gs/adapter.go
> +func (o *storageObjectHandle) newComposer(a *Adapter, srcs ...*storage.ObjectHandle) (*storage.ObjectHandle, *storage.Composer) {
just as you did with `newCopier`, please change `newComposer`, and `newWriter` to return pointers to the structs they create

2024-05-12 14:56 UTC, Jonathan-Rosenberg commented on pkg/block/gs/adapter.go
> +		return &storageObjectHandle{o.Key(a.ServerSideEncryptionCustomerSupplied)}
```suggestion
		o.ObjectHandle = o.Key(a.ServerSideEncryptionCustomerSupplied)
```

2024-05-12 14:56 UTC, Jonathan-Rosenberg commented on pkg/block/gs/adapter.go
> +func (o *storageObjectHandle) prepareWriteHandle(a *Adapter) *storageObjectHandle {
This is classic for the `with` prefix:
```suggestion
func (o *storageObjectHandle) withWriteHandle(a *Adapter) *storageObjectHandle {
```

2024-05-12 14:56 UTC, Jonathan-Rosenberg commented on pkg/block/gs/adapter.go
> +func (o *storageObjectHandle) prepareReadHandle(ctx context.Context, a *Adapter) *storage.ObjectHandle {
`prepareReadHandle` and `prepareWriteHandle` should return the same type for consistency.
Please return a `*storageObjectHandle` in both.

2024-05-12 14:56 UTC, Jonathan-Rosenberg commented on pkg/block/gs/adapter.go
> +			return o.Key(a.ServerSideEncryptionCustomerSupplied)
```suggestion
			o.ObjectHandle = o.Key(a.ServerSideEncryptionCustomerSupplied)
```

2024-05-12 14:56 UTC, Jonathan-Rosenberg commented on pkg/block/gs/adapter.go
> +	return o.ObjectHandle
```suggestion
	return o
```

2024-05-27 08:50 UTC, Jonathan-Rosenberg approved these changes
Thank you @emulatorchen. 
Your contribution is highly appreciated 🙌 
We should also add docs to https://github.com/treeverse/lakeFS/blob/master/docs/howto/deploy/gcp.md, but this could be made on a different PR.

2024-05-27 09:10 UTC, Jonathan-Rosenberg commented
@emulatorchen you would need to sign the [CLA](https://github.com/treeverse/lakeFS/pull/7608#issuecomment-2023411931) in order to contribute...

2024-05-27 10:50 UTC, emulatorchen commented
I think I just screwed up this PR when I tried to fix email on my commits, I will just create another PR for it.

2024-05-27 11:22 UTC, closed without merging