Feature/db read entry
treeverse/lakeFS pull request #783
Opened 2020-10-07 22:02 UTC by tzahij

not to do yet

2020-10-09 09:01 UTC, nopcoder requested changes
Update the PR title to have a meaningful description.
It will help me to add a short description of what you fixed or where in the code you address the issue.
Added Go related comments, but from the change part - it looks we have another version of 'sqEntriesLineage' just to fix the specific problem?

2020-10-09 10:31 UTC, tzahij commented on catalog/db_read_entry.go
> +	}
I have checked this - for some reason IN with one argument consumes more CPU. It may even be because of the driver handling of array

2020-10-09 10:33 UTC, tzahij commented on catalog/db_read_entry.go
> +	rawSelect := sq.Select("path", "physical_address", "creation_date", "size", "checksum", "metadata", "is_expired").
I must do it, because max_commit has special treatment in the following line

2020-10-09 10:39 UTC, tzahij commented on catalog/cataloger_diff.go
> +			Where("branch_id = ? AND merge_source_branch = ? AND merge_type = 'from_parent'", childID, parentID).
Merge tests do not pass without it

2020-10-10 10:50 UTC, tzahij commented on catalog/db_batch_entry_read.go
> +		readExpr, err := LineageSelect(branchID, p, ref.CommitID, tx, true)
Changed to EntryLineageSelect and EntryBrabchSelect

2020-10-12 13:14 UTC, tzahij commented on catalog/cataloger_diff.go
> +			Where("branch_id = ? AND merge_source_branch = ? AND merge_type = 'from_parent'", childID, parentID).
done

2020-10-12 13:16 UTC, tzahij commented on catalog/cataloger_merge_test.go
> +func TestCataloger_MergeFromChildAfterMergeFromFather(t *testing.T) {
done

2020-10-12 21:28 UTC, nopcoder approved these changes

2020-10-15 09:10 UTC, nopcoder approved these changes

2020-10-15 09:32 UTC, merged