Updated and renamed spark-client.md to spark-metadata-client.md
treeverse/lakeFS pull request #8042
Opened 2024-08-02 16:47 UTC by jimmymcnutty

Closes #(Insert issue number closed by this PR)

## Change Description

### Background

Share context and relevant information for the PR: offline discussions, considerations, design decisions etc.

### Bug Fix

If this PR is a bug fix, please let us know about:

1. Problem - The reason for opening the bug
2. Root cause - Discovered root cause after investigation
3. Solution - How the bug was fixed
      
### New Feature

If this PR introduces a new feature, describe it here.

### Testing Details

How were the changes tested?

### Breaking Change?

Does this change break any existing functionality? (API, CLI, Clients)

## Additional info

Logs, outputs, screenshots of changes if applicable (CLI / GUI changes)

### Contact Details

How can we get in touch with you if we need more info? (ex. email@example.com)

2024-08-02 18:58 UTC, ozkatz requested changes
Thanks!

2024-08-02 18:58 UTC, ozkatz commented on docs/reference/spark-metadata-client.md
> +description: The lakeFS Spark client performs operations on lakeFS committed Metadata stored in the object store.
Why captitalize it everywhere?

2024-10-23 20:41 UTC, N-o-Z commented
@jimmymcnutty  hey - we should either fix the comments and merge or close this PR

2024-12-09 21:02 UTC, N-o-Z commented
Closing due to inactivity

2024-12-09 21:02 UTC, closed without merging