PRfD - List Pull Requests UI
treeverse/lakeFS pull request #8171
Opened 2024-09-17 13:25 UTC by itaigilo

Closes #

## Change Description

Creating UI for Listing Pull Requests for a repo.
Including the new `Pull Requests` tab.
 
TBD [screenshot]

2024-09-17 14:13 UTC, itaigilo commented on Makefile
> +gen-ui-watch: $(UI_DIR)/node_modules  ## Build UI web app and watch for changes
Helpful for UI dev.

2024-09-17 14:13 UTC, itaigilo commented on webui/src/lib/api/index.js
> +        console.log("list pulls", {repoId, state, prefix, after, amount})
As written - this is temp, until the API will be ready.

2024-09-17 14:13 UTC, itaigilo commented on webui/src/lib/components/repository/changes.jsx
> +                            <span className="float-start w-100">
For some reason, `width: 100%` was added globally to `float-start`, which is wrong.
Removed it, and added `w-100` to all the places using it (and not overriding).

2024-09-17 14:13 UTC, itaigilo commented on webui/src/lib/components/repository/tabs.jsx
> +                    <GitCompareIcon/> Pull Requests
Using the same icon as `Compare`. We'll need to change one of them.

2024-09-17 14:13 UTC, itaigilo commented on webui/src/lib/components/repository/tabs.jsx
> +                <Link active={active === 'pulls'} href={`/repositories/${repoId}/pulls`} component={NavItem}>
Note - I've used `pulls` (and not `pull-requests`) pretty much everywhere.

2024-09-17 14:13 UTC, itaigilo commented on webui/src/pages/repositories/repository/pulls/pulls.jsx
This is based on the `Tags` page - 
I changed mainly what I needed, and left the rest very similar.

2024-09-17 16:10 UTC, N-o-Z requested changes
Really nice work! And great small and contained PR.
I'm blocking because I believe the tab design is not aligned with the overall lakeFS UI design and needs adjusting.
Since this is a major part of this PR I'm requesting changes

2024-09-17 16:10 UTC, N-o-Z commented on webui/src/pages/repositories/repository/pulls/pulls.jsx
> +        <ListGroup.Item className="pull-row">
Look at the example of commits tab, it should look the same IMO.
Font size, alignment hyperlink marking and the visuals (images and colors) should have the same style.
This tab should look and feel like the other tabs

2024-09-17 16:10 UTC, N-o-Z commented on webui/src/pages/repositories/repository/pulls/pulls.jsx
> +    // TODO: pullState should be persistent in the url and saved as a url param?
state is a query param in GitHub

2024-09-17 17:37 UTC, itaigilo reviewed
@N-o-Z Thanks for the review.

Your comments have been addressed, PTAL again.

2024-09-17 19:14 UTC, N-o-Z approved these changes
I'm approving with 2 concerns:
1. Need to revert the flag!
2. The images still need adjusting - either in this PR or open a new issue for it. But we should have the same visuals as in compare:
![image](https://github.com/user-attachments/assets/62ea5b8a-3f9a-4ba0-beab-dda2f3e6cdcf)

2024-09-17 19:14 UTC, N-o-Z commented on webui/src/lib/components/repository/tabs.jsx
> +const showPulls = true;
Need to revert this to `false` 😃

2024-09-18 05:46 UTC, itaigilo commented
@N-o-Z thanks for spotting the flag - reverted.

Regarding how the source/dest looks like: 
I generally agree - I honestly don't have a clear understanding on how this should look from the PRD,
So I think that the best way to approach this will be to schedule a UI review once all the functionality is there.
I'll schedule such review, and will add an Issue for it.

2024-09-18 06:03 UTC, merged