PRfD - Create PR Details page
treeverse/lakeFS pull request #8185
Opened 2024-09-18 16:36 UTC by itaigilo

Closes #8175 

## Change Description

Create the page showing the PR Details.

Also handles the navigation, and creates a scaffold fo the Create PR page (as part of it).

-----

TBD - Screenshot.

2024-09-19 15:28 UTC, itaigilo commented on webui/src/lib/api/index.js
> +            resolve({
Accidentally formatted this. White spaces only from here in this file.

2024-09-19 15:29 UTC, itaigilo commented on webui/src/constants.ts
> +export enum PullStatus {
This seems like a better place for this.

2024-09-19 23:49 UTC, N-o-Z requested changes
It looks very very nice.
The only reason I'm requesting changes is that there seems to be some mix up with the PR titles and branch src-dest when going from lists to the actual PR.
This is how it looks in the list:
![image](https://github.com/user-attachments/assets/85459640-5a40-4a90-a407-814abcfc9bbc)
And this is how it looks when I press on the PR (notice the title, src and dest branches):
![image](https://github.com/user-attachments/assets/bc182f7f-ae57-4315-b771-49a058fbd71f)

2024-09-19 23:51 UTC, N-o-Z commented
@itaigilo Since we already merged Get/Create E2E you can actually implement it now.
Also, I don't see a reason not to implement the Merge logic already since this is unrelated to the PR logic

2024-09-20 05:35 UTC, itaigilo commented
> The only reason I'm requesting changes is that there seems to be some mix up with the PR titles and branch src-dest when going from lists to the actual PR. 

@N-o-Z If I understand you correctly - the difference is because of the mock data (which is different between the GET and LIST API calls).

And regarding your comment about integrating first - 
I'd be happy to, but currently I have no real PRs data to test the integration of the Details page.
My plan is to merge this PR, continue to creating the Create page (which will be connected to the API and will create a real PR in the KV), and then integrate the rest.

2024-09-20 15:54 UTC, N-o-Z commented
> > The only reason I'm requesting changes is that there seems to be some mix up with the PR titles and branch src-dest when going from lists to the actual PR.
> 
> @N-o-Z If I understand you correctly - the difference is because of the mock data (which is different between the GET and LIST API calls).
> 
> And regarding your comment about integrating first - I'd be happy to, but currently I have no real PRs data to test the integration of the Details page. My plan is to merge this PR, continue to creating the Create page (which will be connected to the API and will create a real PR in the KV), and then integrate the rest.

Thanks - I guess I missed that!

2024-09-20 15:54 UTC, N-o-Z approved these changes
LGTM!

2024-09-22 04:37 UTC, merged